import { Spot } from '@/types';

export const spots: Spot[] = [
  {
      id: 'moledo', slug: 'moledo', name: 'Moledo do Minho', nameEn: 'Moledo do Minho',
      region: 'Caminha', regionEn: 'Caminha', lat: 41.848, lon: -8.863,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, NE', bestSwell: 'W, NW',
      description: 'Praia de areia fina no extremo norte de Portugal. Ondas potentes com pouca multidão. Vista para a Espanha do outro lado do rio Minho.',
      descriptionEn: 'Fine sand beach at the extreme north of Portugal. Powerful waves with little crowd. View of Spain across the Minho river.',
      facilities: ['Estacionamento', 'Restaurante', 'WC'],
      hazards: ['Correntes fortes', 'Água fria']
    },
  {
      id: 'vila-praia-ancora', slug: 'vila-praia-ancora', name: 'Vila Praia de Âncora', nameEn: 'Vila Praia de Ancora',
      region: 'Viana do Castelo', regionEn: 'Viana do Castelo', lat: 41.817, lon: -8.850,
      coastOrientation: 270,
      type: 'surf', difficulty: 'beginner', bestWind: 'E, NE', bestSwell: 'W, NW',
      description: 'A melhor praia para aprender surf no distrito de Viana. Ondas suaves, praia extensa e paisagem natural deslumbrante. Perfeita para famílias.',
      descriptionEn: 'The best beach to learn surf in Viana district. Gentle waves, extensive beach and stunning natural landscape. Perfect for families.',
      facilities: ['Estacionamento', 'Escola surf', 'Restaurantes', 'Alojamento', 'WC'],
      hazards: ['Correntes moderadas']
    },
  {
      id: 'afife', slug: 'afife', name: 'Afife (Praia da Arda)', nameEn: 'Afife (Arda Beach)',
      region: 'Viana do Castelo', regionEn: 'Viana do Castelo', lat: 41.780, lon: -8.860,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Destino de surf e windsurf desde os anos 70! Ondas de qualidade com ventos fortes ocasionais. Um dos spots mais icónicos do norte.',
      descriptionEn: 'Surfing and windsurfing destination since the 70s! Quality waves with occasional strong winds. One of the most iconic northern spots.',
      facilities: ['Estacionamento', 'Escola surf', 'Restaurante', 'WC'],
      hazards: ['Vento forte', 'Correntes', 'Exposto ao vento']
    },
  {
      id: 'castelo-neiva', slug: 'castelo-neiva', name: 'Castelo do Neiva', nameEn: 'Castelo do Neiva',
      region: 'Viana do Castelo', regionEn: 'Viana do Castelo', lat: 41.750, lon: -8.820,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Praia com bandeira azul e ambiente tranquilo. Beach break consistente com múltiplos picos. Clube náutico na zona.',
      descriptionEn: 'Blue flag beach with tranquil atmosphere. Consistent beach break with multiple peaks. Nautical club in the area.',
      facilities: ['Estacionamento', 'Restaurante', 'Clube Nautico', 'WC'],
      hazards: ['Rochas submersas', 'Correntes']
    },
  {
      id: 'amorosa', slug: 'amorosa', name: 'Praia da Amorosa', nameEn: 'Amorosa Beach',
      region: 'Viana do Castelo', regionEn: 'Viana do Castelo', lat: 41.700, lon: -8.850,
      coastOrientation: 270,
      type: 'kitesurf', difficulty: 'intermediate', bestWind: 'N, NW', bestSwell: 'S, SW',
      description: 'Spot de kitesurf ao lado do Cabedelo. Água plana ideal para freestyle e foil. Menos crowd que o Cabedelo principal.',
      descriptionEn: 'Kitesurf spot next to Cabedelo. Flat water ideal for freestyle and foil. Less crowded than main Cabedelo.',
      facilities: ['Estacionamento', 'Escola kite', 'WC'],
      hazards: ['Pedras entre Cabedelo e Amorosa', 'Mare']
    },
  {
      id: 'cabedelo', slug: 'cabedelo', name: 'Cabedelo', nameEn: 'Cabedelo',
      region: 'Viana do Castelo', regionEn: 'Viana do Castelo', lat: 41.687, lon: -8.845,
      coastOrientation: 270,
      type: 'kitesurf', difficulty: 'beginner', bestWind: 'NW, N', bestSwell: 'SW',
      description: 'Um dos melhores spots de kitesurf do Norte. Água plana na barra do rio Lima. Vento térmico de NW consistente. Épico para iniciantes!',
      descriptionEn: 'One of the best kitesurf spots in the north. Flat water at the Lima river bar. Consistent NW thermal wind. Epic for beginners!',
      facilities: ['Estacionamento', 'Escolas kite', 'Aluguer', 'WC'],
      hazards: ['Tráfego de barcos', 'Correntes na foz']
    },
  {
      id: 'foil-cabedelo', slug: 'foil-cabedelo', name: 'Cabedelo - Foil', nameEn: 'Cabedelo - Foil',
      region: 'Viana do Castelo', regionEn: 'Viana do Castelo', lat: 41.687, lon: -8.845,
      coastOrientation: 270,
      type: 'foil', difficulty: 'intermediate', bestWind: 'NW, N', bestSwell: 'Rio',
      description: 'Água plana na barra do rio Lima — perfeita para wing foil. Vento térmico de NW consistente. Spot de foil no norte de Portugal.',
      descriptionEn: 'Flat water at the Lima river bar — perfect for wing foil. Consistent NW thermal wind. Foil spot in northern Portugal.',
      facilities: ['Estacionamento', 'Escola foil', 'Aluguer', 'WC'],
      hazards: ['Tráfego de barcos', 'Correntes na foz']
    },
  {
      id: 'ofir', slug: 'ofir', name: 'Ofir', nameEn: 'Ofir',
      region: 'Esposende', regionEn: 'Esposende', lat: 41.548, lon: -8.789,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Beach break potente com ondas de qualidade. Pouco crowd comparado com outras praias do norte. Fundo de areia variável.',
      descriptionEn: 'Powerful beach break with quality waves. Less crowded than other northern beaches. Variable sand bottom.',
      facilities: ['Estacionamento', 'Restaurante', 'WC'],
      hazards: ['Correntes', 'Ressaca forte']
    },
  {
      id: 'esposende', slug: 'esposende', name: 'Esposende', nameEn: 'Esposende',
      region: 'Braga', regionEn: 'Braga', lat: 41.536, lon: -8.783,
      coastOrientation: 270,
      type: 'kitesurf', difficulty: 'intermediate', bestWind: 'NW, N', bestSwell: 'SW',
      description: 'Lagoa, foz do rio e praia aberta — três spots num só. Água plana na lagoa, ondas no oceano. Versátil e consistente.',
      descriptionEn: 'Lagoon, river mouth and open beach — three spots in one. Flat water in the lagoon, waves in the ocean. Versatile and consistent.',
      compatibleSports: ['kitesurf', 'foil', 'windsurf', 'wakeboard'],
      facilities: ['Estacionamento', 'Escolas kite', 'Aluguer', 'WC'],
      hazards: ['Correntes na foz', 'Rochas na lagoa']
    },
  {
      id: 'fao', slug: 'fao', name: 'Fão', nameEn: 'Fao',
      region: 'Esposende', regionEn: 'Esposende', lat: 41.510, lon: -8.770,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Spot junto a Ofir com beach break consistente. Praia menos explorada, ideal para escapar da multidão. Fundo de areia variável.',
      descriptionEn: 'Spot next to Ofir with consistent beach break. Less explored beach, ideal to escape crowds. Variable sand bottom.',
      facilities: ['Estacionamento', 'Restaurante', 'WC'],
      hazards: ['Ressaca forte', 'Correntes']
    },
  {
      id: 'apulia', slug: 'apulia', name: 'Apúlia', nameEn: 'Apulia',
      region: 'Esposende', regionEn: 'Esposende', lat: 41.480, lon: -8.760,
      coastOrientation: 270,
      type: 'surf', difficulty: 'beginner', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Praia famosa do Norte com moinhos de vento como cenário. Ondas suaves perfeitas para iniciantes e longboard. Ambiente único.',
      descriptionEn: 'Famous Northern beach with windmills as scenery. Gentle waves perfect for beginners and longboard. Unique atmosphere.',
      facilities: ['Estacionamento', 'Restaurante', 'WC', 'Moinhos de vento'],
      hazards: ['Correntes', 'Multidao no verao']
    },
  {
      id: 'povoa-varzim', slug: 'povoa-varzim', name: 'Póvoa do Varzim', nameEn: 'Povoa do Varzim',
      region: 'Porto', regionEn: 'Porto', lat: 41.377, lon: -8.760,
      coastOrientation: 270,
      type: 'surf', difficulty: 'beginner', bestWind: 'E, NE', bestSwell: 'W, NW',
      description: 'Praia longa com ondas suaves perfeitas para iniciantes. Escolas de surf com boa reputação. Ambiente familiar.',
      descriptionEn: 'Long beach with gentle waves perfect for beginners. Reputable surf schools. Family-friendly atmosphere.',
      facilities: ['Estacionamento', 'Escolas surf', 'Restaurantes', 'WC'],
      hazards: ['Correntes moderadas']
    },
  {
      id: 'azurara', slug: 'azurara', name: 'Azurara', nameEn: 'Azurara',
      region: 'Vila do Conde', regionEn: 'Vila do Conde', lat: 41.360, lon: -8.750,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Uma das melhores praias de surf do Norte de Portugal! Orientação geográfica perfeita para ondas. Beach break com múltiplos picos.',
      descriptionEn: 'One of the best surf beaches in Northern Portugal! Perfect geographic orientation for waves. Beach break with multiple peaks.',
      facilities: ['Estacionamento', 'Escola surf', 'Restaurantes', 'WC'],
      hazards: ['Correntes', 'Ressaca forte']
    },
  {
      id: 'leca-palmeira', slug: 'leca-palmeira', name: 'Leça da Palmeira', nameEn: 'Leca da Palmeira',
      region: 'Porto', regionEn: 'Porto', lat: 41.192, lon: -8.709,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Praia com bandeira azul ao lado de Matosinhos. Beach break potente com ondas mais hollow. Pool de mares famoso nas proximidades.',
      descriptionEn: 'Blue flag beach next to Matosinhos. Powerful beach break with hollower waves. Famous tidal pool nearby.',
      facilities: ['Estacionamento', 'Restaurante', 'Piscina de Mares', 'WC'],
      hazards: ['Correntes', 'Ressaca']
    },
  {
      id: 'matosinhos', slug: 'matosinhos', name: 'Matosinhos', nameEn: 'Matosinhos',
      region: 'Porto', regionEn: 'Porto', lat: 41.177, lon: -8.692,
      coastOrientation: 270,
      type: 'surf', difficulty: 'beginner', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'A melhor praia para aprender surf em Portugal. Sem correntes, sem rochas, ondas suaves e consistentes. O local mais seguro do norte.',
      descriptionEn: 'The best beach to learn surf in Portugal. No rip currents, no rocks, soft and consistent waves. The safest spot in the north.',
      facilities: ['Estacionamento', 'Escolas surf', 'Restaurantes', 'Metro', 'WC'],
      hazards: ['Multidão nos fins de semana']
    },
  {
      id: 'espinho', slug: 'espinho', name: 'Espinho', nameEn: 'Espinho',
      region: 'Porto', regionEn: 'Porto', lat: 41.007, lon: -8.640,
      coastOrientation: 270,
      type: 'surf', difficulty: 'advanced', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'A LENDARIA "Direita do Casino"! Onda tubular que forma junto ao molhe do casino. Uma das ondas mais famosas do Norte. Sede de etapas do World Junior Tour.',
      descriptionEn: 'The LEGENDARY "Casino Right"! Barrel wave forming next to the casino breakwater. One of the most famous waves in the North. Host of World Junior Tour stages.',
      facilities: ['Estacionamento', 'Escola surf', 'Restaurantes', 'Casino', 'WC'],
      hazards: ['Ondas pesadas', 'Molhe', 'Locals']
    },
  {
      id: 'esmoriz', slug: 'esmoriz', name: 'Esmoriz', nameEn: 'Esmoriz',
      region: 'Ovar', regionEn: 'Ovar', lat: 40.960, lon: -8.620,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Considerada pelo Evening Times a 2ª melhor zona de surf do MUNDO! Beach break de 6km com múltiplos picos. Pinhal ao fundo. Spot selvagem e pouco crowd.',
      descriptionEn: 'Ranked by Evening Times as the 2nd best surf area in the WORLD! 6km beach break with multiple peaks. Pine forest backdrop. Wild and uncrowded spot.',
      facilities: ['Estacionamento', 'Escola surf', 'Restaurantes', 'Camping', 'WC'],
      hazards: ['Correntes', 'Ressaca forte']
    },
  {
      id: 'cortegaca', slug: 'cortegaca', name: 'Cortegaça', nameEn: 'Cortegaca',
      region: 'Ovar', regionEn: 'Ovar', lat: 40.940, lon: -8.610,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Beach break consistente famoso pelo festival de surf nocturno. Ondas de qualidade com pouco crowd. Pinhal ao lado.',
      descriptionEn: 'Consistent beach break famous for night surfing festival. Quality waves with little crowd. Pine forest next to it.',
      facilities: ['Estacionamento', 'Restaurante', 'WC'],
      hazards: ['Correntes', 'Ressaca']
    },
  {
      id: 'maceda', slug: 'maceda', name: 'Maceda', nameEn: 'Maceda',
      region: 'Ovar', regionEn: 'Ovar', lat: 40.930, lon: -8.600,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Beach break selvagem com dunas imensas. Spot pouco explorado, ideal para escapar da multidão. Ondas de qualidade com crowd minimo.',
      descriptionEn: 'Wild beach break with huge dunes. Little explored spot, ideal to escape crowds. Quality waves with minimal crowd.',
      facilities: ['Estacionamento', 'WC'],
      hazards: ['Correntes fortes', 'Isolamento']
    },
  {
      id: 'murtosa', slug: 'murtosa', name: 'Murtosa', nameEn: 'Murtosa',
      region: 'Aveiro', regionEn: 'Aveiro', lat: 40.733, lon: -8.650,
      coastOrientation: 270,
      type: 'kitesurf', difficulty: 'beginner', bestWind: 'NW, N', bestSwell: 'Rio',
      description: 'Laguna de água plana perfeita para kitesurf e windsurf. Vento térmico de NW consistente. Uma das melhores lagoas do centro de Portugal para iniciantes.',
      descriptionEn: 'Flat water lagoon perfect for kitesurfing and windsurfing. Consistent NW thermal wind. One of the best lagoons in central Portugal for beginners.',
      compatibleSports: ['kitesurf', 'windsurf', 'foil', 'sup'],
      blueFlag: true,
      facilities: ['Estacionamento', 'Escola kite', 'WC'],
      hazards: ['Bancos de areia na maré baixa']
    },
  {
      id: 'furadouro', slug: 'furadouro', name: 'Furadouro', nameEn: 'Furadouro',
      region: 'Ovar', regionEn: 'Ovar', lat: 40.650, lon: -8.670,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Praia extensa com ondas consistentes e múltiplos picos. Beach break popular entre surfistas do Porto e Aveiro. Funciona em quase todas as marés.',
      descriptionEn: 'Extensive beach with consistent waves and multiple peaks. Popular beach break among Porto and Aveiro surfers. Works on almost all tides.',
      compatibleSports: ['surf', 'bodyboard'],
      blueFlag: true,
      facilities: ['Estacionamento', 'Escola surf', 'Restaurantes', 'WC'],
      hazards: ['Correntes', 'Multidão no verão']
    },
  {
      id: 'sao-jacinto', slug: 'sao-jacinto', name: 'São Jacinto', nameEn: 'Sao Jacinto',
      region: 'Aveiro', regionEn: 'Aveiro', lat: 40.686, lon: -8.729,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Reserva Natural das Dunas com surf de qualidade. Praia selvagem acessível apenas de barco. Ondas consistentes e crowd zero.',
      descriptionEn: 'Dunes Nature Reserve with quality surf. Wild beach accessible only by boat. Consistent waves and zero crowd.',
      facilities: ['Barco', 'Restaurante', 'WC'],
      hazards: ['Acesso de barco apenas', 'Correntes']
    },
  {
      id: 'costa-nova', slug: 'costa-nova', name: 'Costa Nova', nameEn: 'Costa Nova',
      region: 'Aveiro', regionEn: 'Aveiro', lat: 40.620, lon: -8.747,
      coastOrientation: 270,
      type: 'windsurf', difficulty: 'intermediate', bestWind: 'N, NW', bestSwell: 'W',
      description: 'Spot clássico de windsurf no centro de Portugal. Ondas e vento de NW. Cenário único com as casas listradas.',
      descriptionEn: 'Classic windsurf spot in central Portugal. Waves and NW wind. Unique scenery with the striped houses.',
      facilities: ['Estacionamento', 'Escola windsurf', 'WC'],
      hazards: ['Correntes', 'Água fria']
    },
  {
      id: 'quiaios', slug: 'quiaios', name: 'Quiaios', nameEn: 'Quiaios',
      region: 'Figueira da Foz', regionEn: 'Figueira da Foz', lat: 40.220, lon: -8.890,
      coastOrientation: 270,
      type: 'surf', difficulty: 'beginner', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Praia longa e selvagem no norte da Figueira da Foz. Ondas suaves ideais para iniciantes. Pouco crowd e ambiente natural preservado.',
      descriptionEn: 'Long and wild beach north of Figueira da Foz. Gentle waves ideal for beginners. Low crowd and preserved natural environment.',
      facilities: ['Estacionamento', 'WC'],
      hazards: ['Correntes moderadas', 'Sem vigilância']
    },
  {
      id: 'figueira-foz', slug: 'figueira-foz', name: 'Figueira da Foz (Buarcos)', nameEn: 'Figueira da Foz (Buarcos)',
      region: 'Figueira da Foz', regionEn: 'Figueira da Foz', lat: 40.150, lon: -8.870,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, NE', bestSwell: 'W, NW',
      description: 'Uma das praias mais emblemáticas do centro de Portugal. Ondas potentes e consistentes, palco de campeonatos nacionais. O molhe divide a praia em dois picos distintos.',
      descriptionEn: 'One of the most emblematic beaches in central Portugal. Powerful and consistent waves, host of national championships. The jetty divides the beach into two distinct peaks.',
      compatibleSports: ['surf', 'bodyboard'],
      blueFlag: true,
      facilities: ['Estacionamento', 'Escola surf', 'Restaurantes', 'Alojamento', 'WC'],
      hazards: ['Correntes fortes', 'Rochas junto ao molhe']
    },
  {
      id: 'leirosa', slug: 'leirosa', name: 'Leirosa', nameEn: 'Leirosa',
      region: 'Figueira da Foz', regionEn: 'Figueira da Foz', lat: 40.057, lon: -8.890,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, NE', bestSwell: 'W, NW',
      description: 'Praia rústica e pouco frequentada entre a Figueira da Foz e Nazaré. Beach break potente com ondas tubulares em dias bons. Para surfistas que gostam de isolamento.',
      descriptionEn: 'Rustic and little-frequented beach between Figueira da Foz and Nazaré. Powerful beach break with tubular waves on good days. For surfers who enjoy isolation.',
      facilities: ['Estacionamento'],
      hazards: ['Correntes fortes', 'Sem infraestruturas']
    },
  {
      id: 'castelo-bode', slug: 'castelo-bode', name: 'Castelo de Bode', nameEn: 'Castelo de Bode',
      region: 'Santarém', regionEn: 'Santarem', lat: 39.600, lon: -8.300,
      coastOrientation: 270,
      type: 'wakeboard', difficulty: 'all', bestWind: 'Vário', bestSwell: 'Lagoa',
      description: 'Maior resort de wakeboard da Europa! 5 cable parks em 30km de lagoa. Água cristalina e plana. Perfeito para iniciantes a pros.',
      descriptionEn: 'Biggest wakeboard resort in Europe! 5 cable parks along 30km of lake. Crystal clear flat water. Perfect from beginners to pros.',
      facilities: ['Estacionamento', '5 Cable Parks', 'Escola wake', 'Aluguer', 'Restaurante', 'Alojamento'],
      hazards: ['Outros riders', 'Barcos']
    },
  {
      id: 'nazare', slug: 'nazare', name: 'Nazaré', nameEn: 'Nazare',
      region: 'Oeste', regionEn: 'West Coast', lat: 39.597, lon: -9.073,
      coastOrientation: 270,
      type: 'big-wave', difficulty: 'expert', bestWind: 'N, NNE', bestSwell: 'W, WNW',
      description: 'Famoso pelas maiores ondas do mundo. Praia do Norte é o palco do Big Wave Surfing. Canal submarino amplifica ondas gigantescas.',
      descriptionEn: 'Famous for the biggest waves in the world. Praia do Norte is the stage for Big Wave Surfing. Underwater canyon amplifies giant waves.',
      facilities: ['Estacionamento', 'Restaurantes', 'Salva-vidas', 'WC'],
      hazards: ['Ondas gigantescas', 'Correntes fortes', 'Rochas submersas']
    },
  {
      id: 'foz-arelho', slug: 'foz-arelho', name: 'Foz do Arelho', nameEn: 'Foz do Arelho',
      region: 'Oeste', regionEn: 'West Coast', lat: 39.427, lon: -9.210,
      coastOrientation: 270,
      type: 'kitesurf', difficulty: 'beginner', bestWind: 'N, NNE', bestSwell: 'W',
      description: 'Lagoa de Óbidos perfeita para iniciantes. Água plana, vento side-onshore. Escolas e aluguer.',
      descriptionEn: 'Obidos Lagoon perfect for beginners. Flat water, side-onshore wind. Schools and rental.',
      facilities: ['Estacionamento', 'Escolas kite', 'Aluguer', 'Restaurantes', 'WC'],
      hazards: ['Tráfego de iniciantes', 'Maré baixa']
    },
  {
      id: 'foil-foz-arelho', slug: 'foil-foz-arelho', name: 'Foz do Arelho - Foil', nameEn: 'Foz do Arelho - Foil',
      region: 'Oeste', regionEn: 'West Coast', lat: 39.427, lon: -9.210,
      coastOrientation: 270,
      type: 'foil', difficulty: 'beginner', bestWind: 'N, NNE', bestSwell: 'Lagoa',
      description: 'Lagoa de Óbidos perfeita para wing foil e kite foil. Água plana, vento side-onshore. Escolas com equipamento de foil.',
      descriptionEn: 'Obidos Lagoon perfect for wing foil and kite foil. Flat water, side-onshore wind. Schools with foil equipment.',
      facilities: ['Estacionamento', 'Escolas foil', 'Aluguer', 'Restaurantes', 'WC'],
      hazards: ['Tráfego de iniciantes', 'Maré baixa']
    },
  {
      id: 'obidos-lagoon', slug: 'obidos-lagoon', name: 'Lagoa de Óbidos', nameEn: 'Obidos Lagoon',
      region: 'Óbidos', regionEn: 'Obidos', lat: 39.400, lon: -9.220,
      coastOrientation: 270,
      type: 'kitesurf', difficulty: 'beginner', bestWind: 'NW, N', bestSwell: 'Lagoa',
      description: 'A maior lagoa de água salgada de Portugal. Água plana e rasa, ideal para aprender kitesurf, windsurf, wing foil e SUP. Vento térmico de NW amplificado pelo efeito venturi.',
      descriptionEn: 'The largest saltwater lagoon in Portugal. Flat and shallow water, ideal for learning kitesurfing, windsurfing, wing foiling and SUP. NW thermal wind amplified by the venturi effect.',
      compatibleSports: ['kitesurf', 'windsurf', 'foil', 'sup'],
      blueFlag: true,
      facilities: ['Estacionamento', 'Escolas kite', 'Escolas windsurf', 'Escolas wing foil', 'WC', 'Restaurantes'],
      hazards: ['Conchas no fundo', 'Bancos de areia na maré baixa'],
      localTips: {
        bestTide: 'Maré média a alta para mais profundidade',
        bestTideEn: 'Mid to high tide for more depth',
        parking: 'Gratuito junto à lagoa',
        parkingEn: 'Free near the lagoon'
      }
    },
  {
      id: 'baleal', slug: 'baleal', name: 'Baleal', nameEn: 'Baleal',
      region: 'Peniche', regionEn: 'Peniche', lat: 39.372, lon: -9.338,
      coastOrientation: 270,
      type: 'surf', difficulty: 'beginner', bestWind: 'N, NE', bestSwell: 'W, NW',
      description: 'Cantinho da Baía — ondas suaves protegidas da ilha. Perfeito para iniciantes e intermediários. Vários picos ao longo da baía.',
      descriptionEn: 'Cantinho da Baía — soft waves protected by the island. Perfect for beginners and intermediates. Multiple peaks along the bay.',
      facilities: ['Estacionamento', 'Escolas surf', 'Restaurantes', 'WC'],
      hazards: ['Multidão na época alta']
    },
  {
      id: 'supertubos', slug: 'supertubos', name: 'Supertubos', nameEn: 'Supertubos',
      region: 'Peniche', regionEn: 'Peniche', lat: 39.338, lon: -9.359,
      coastOrientation: 270,
      type: 'surf', difficulty: 'advanced', bestWind: 'N, NE', bestSwell: 'W, NW',
      description: 'Onda tubular perfeita, palco do WSL Championship Tour. Tubos rápidos e potentes sobre areia.',
      descriptionEn: 'Perfect barreling wave, WSL Championship Tour venue. Fast and powerful tubes over sand.',
      facilities: ['Estacionamento', 'Escola de surf', 'Aluguer', 'WC'],
      hazards: ['Correntes', 'Ressaca forte']
    },
  {
      id: 'coxos', slug: 'coxos', name: 'Coxos', nameEn: 'Coxos',
      region: 'Ericeira', regionEn: 'Ericeira', lat: 38.999, lon: -9.430,
      coastOrientation: 270,
      type: 'surf', difficulty: 'advanced', bestWind: 'N, NE', bestSwell: 'NW, W',
      description: 'Reef break poderoso e tubar. Uma das melhores ondas de Portugal — direita longa, íngreme, ocas. Apenas para experts.',
      descriptionEn: 'Powerful reef break barrel. One of the best waves in Portugal — long, steep, hollow right. Experts only.',
      facilities: ['Estacionamento limitado', 'Acesso íngreme'],
      hazards: ['Rochas afiadas', 'Locals agressivos', 'Pouco profundo']
    },
  {
      id: 'ribeira-ilhas', slug: 'ribeira-ilhas', name: "Ribeira d'Ilhas", nameEn: "Ribeira d'Ilhas",
      region: 'Ericeira', regionEn: 'Ericeira', lat: 38.989, lon: -9.422,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'N, NE', bestSwell: 'NW, W',
      description: 'Onda direita clássica da Ericeira, palco do WSL. Uma das mais consistentes de Portugal. Longa, perfeita, tubos incríveis.',
      descriptionEn: 'Classic Ericeira right-hand wave, WSL venue. One of the most consistent in Portugal. Long, perfect, incredible barrels.',
      facilities: ['Estacionamento', 'Café', 'WC'],
      hazards: ['Locals', 'Rochas', 'Multidão']
    },
  {
      id: 'foz-sizandro', slug: 'foz-sizandro', name: 'Foz do Sizandro', nameEn: 'Foz do Sizandro',
      region: 'Torres Vedras', regionEn: 'Torres Vedras', lat: 39.080, lon: -9.350,
      coastOrientation: 270,
      type: 'surf', difficulty: 'beginner', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Praia familiar na foz do rio Sizandro. Ondas suaves e consistentes, perfeitas para iniciantes. Ambiente tranquilo e pouco crowd.',
      descriptionEn: 'Family beach at the mouth of the Sizandro river. Gentle and consistent waves, perfect for beginners. Tranquil atmosphere and low crowd.',
      facilities: ['Estacionamento', 'Restaurante', 'WC'],
      hazards: ['Correntes na foz'],
      compatibleSports: ['surf', 'bodyboard', 'sup'],
      blueFlag: true
    },
  {
      id: 'empa', slug: 'empa', name: 'Praia da Empa (Ericeira)', nameEn: 'Praia da Empa (Ericeira)',
      region: 'Ericeira', regionEn: 'Ericeira', lat: 38.985, lon: -9.425,
      coastOrientation: 270,
      type: 'surf', difficulty: 'advanced', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Pequena praia com duas jóias: Pedra Branca e Reef. Ondas velozes e potentes que atraem bodyboarders e surfistas avançados ao longo do ano.',
      descriptionEn: 'Small beach with two gems: Pedra Branca and Reef. Fast and powerful waves that attract bodyboarders and advanced surfers year-round.',
      facilities: ['Estacionamento'],
      hazards: ['Rochas', 'Ondas tubulares', 'Correntes'],
      compatibleSports: ['surf', 'bodyboard']
    },
  {
      id: 'sao-lourenco', slug: 'sao-lourenco', name: 'São Lourenço (Ericeira)', nameEn: 'Sao Lourenco (Ericeira)',
      region: 'Ericeira', regionEn: 'Ericeira', lat: 38.980, lon: -9.420,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'N, NW', bestSwell: 'W, NW',
      description: 'O spot mais a norte da Reserva Mundial de Surf da Ericeira. Baía abrigada onde o vento de NW é cross-shore ou ligeiramente offshore. Direitas longas e potentes a partir de 1.5m.',
      descriptionEn: 'The northernmost spot of Ericeira World Surfing Reserve. Sheltered bay where NW wind is cross-shore or slightly offshore. Long and powerful rights from 1.5m.',
      facilities: ['Estacionamento', 'Restaurante', 'WC'],
      hazards: ['Rochas submersas', 'Correntes'],
      compatibleSports: ['surf', 'bodyboard']
    },
  {
      id: 'pedra-branca', slug: 'pedra-branca', name: 'Pedra Branca (Ericeira)', nameEn: 'Pedra Branca (Ericeira)',
      region: 'Ericeira', regionEn: 'Ericeira', lat: 38.975, lon: -9.415,
      coastOrientation: 270,
      type: 'surf', difficulty: 'advanced', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Reef break poderoso considerado irmão gémeo do Coxos. Ondas velozes, tubulares e frequentes. Um dos picos mais técnicos da Ericeira. Apenas para surfistas experientes.',
      descriptionEn: 'Powerful reef break considered twin brother of Coxos. Fast, tubular and frequent waves. One of the most technical peaks in Ericeira. For experienced surfers only.',
      facilities: ['Estacionamento'],
      hazards: ['Rochas', 'Ondas potentes', 'Correntes'],
      compatibleSports: ['surf', 'bodyboard']
    },
  {
      id: 'sao-sebastiao', slug: 'sao-sebastiao', name: 'São Sebastião (Ericeira)', nameEn: 'Sao Sebastiao (Ericeira)',
      region: 'Ericeira', regionEn: 'Ericeira', lat: 38.970, lon: -9.420,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Praia de surf mais acessível da Ericeira. Ondas desafiadoras mas gerenciáveis. Múltiplos picos ao longo da praia. Excelente para surfistas em evolução.',
      descriptionEn: 'Most accessible surf beach in Ericeira. Challenging but manageable waves. Multiple peaks along the beach. Excellent for evolving surfers.',
      facilities: ['Estacionamento', 'Escola surf', 'Restaurantes', 'WC'],
      hazards: ['Correntes', 'Rochas'],
      compatibleSports: ['surf', 'bodyboard'],
      blueFlag: true
    },
  {
      id: 'foz-lizandro', slug: 'foz-lizandro', name: 'Foz do Lizandro', nameEn: 'Foz do Lizandro',
      region: 'Ericeira', regionEn: 'Ericeira', lat: 38.936, lon: -9.392,
      coastOrientation: 270,
      type: 'surf', difficulty: 'beginner', bestWind: 'N, NE', bestSwell: 'S, SW',
      description: 'Praia de areia em forma de L no estuário do rio Lizandro. Ondas para todos os níveis. Reef breaks Lage dos Tubos e Limipicos no norte.',
      descriptionEn: 'L-shaped sand beach at the Lizandro river estuary. Waves for all levels. Lage dos Tubos and Limipicos reef breaks in the north.',
      facilities: ['Estacionamento', 'Restaurantes', 'Escola surf', 'WC'],
      hazards: ['Correntes na maré vazante', 'Rochas no reef']
    },
  {
      id: 'praia-grande-sintra', slug: 'praia-grande-sintra', name: 'Praia Grande (Sintra)', nameEn: 'Praia Grande (Sintra)',
      region: 'Sintra', regionEn: 'Sintra', lat: 38.820, lon: -9.470,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Extensa praia entre falésias, famosa pelo bodyboard e surf. Palco do Mundial de Bodyboard. Ondas potentes com múltiplos picos. Uma das praias mais bonitas da linha de Sintra.',
      descriptionEn: 'Extensive beach between cliffs, famous for bodyboarding and surfing. Host of the World Bodyboard Championship. Powerful waves with multiple peaks. One of the most beautiful beaches on the Sintra coast.',
      compatibleSports: ['surf', 'bodyboard'],
      blueFlag: true,
      facilities: ['Estacionamento', 'Escola surf', 'Restaurantes', 'WC'],
      hazards: ['Correntes fortes', 'Rochas submersas']
    },
  {
      id: 'adraga', slug: 'adraga', name: 'Praia da Adraga', nameEn: 'Adraga Beach',
      region: 'Sintra', regionEn: 'Sintra', lat: 38.790, lon: -9.490,
      coastOrientation: 270,
      type: 'surf', difficulty: 'advanced', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Praia selvagem entre falésias dramáticas. Ondas potentes e tubulares. Spot avançado com cenário de cortar a respiração. Uma das praias mais fotografadas de Portugal.',
      descriptionEn: 'Wild beach between dramatic cliffs. Powerful and tubular waves. Advanced spot with breathtaking scenery. One of the most photographed beaches in Portugal.',
      facilities: ['Estacionamento', 'Restaurante'],
      hazards: ['Rochas', 'Ondas potentes', 'Correntes'],
      compatibleSports: ['surf', 'bodyboard']
    },
  {
      id: 'guincho', slug: 'guincho', name: 'Guincho', nameEn: 'Guincho',
      region: 'Cascais', regionEn: 'Cascais', lat: 38.733, lon: -9.473,
      coastOrientation: 270,
      type: 'multisport', difficulty: 'intermediate', bestWind: 'N, NNW', bestSwell: 'SW, W',
      description: 'Spot icónico de kitesurf e windsurf. Vento térmico Nortada consistente no verão. Melhor vento de Portugal.',
      descriptionEn: 'Iconic kitesurf and windsurf spot. Consistent thermal Nortada wind in summer. Best wind in Portugal.',
      compatibleSports: ['surf', 'kitesurf', 'windsurf'],
      facilities: ['Estacionamento', 'Restaurante', 'Escola kite', 'WC'],
      hazards: ['Vento forte', 'Correntes', 'Rochas']
    },
  {
      id: 'praia-vitoria', slug: 'praia-vitoria', name: 'Praia da Vitória', nameEn: 'Praia da Vitoria',
      region: 'Terceira', regionEn: 'Terceira', lat: 38.730, lon: -27.066,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, NE', bestSwell: 'W, NW',
      description: 'Baía abrigada na Terceira com ondas consistentes. Praia extensa com areia clara. Cenário único dos Açores centrais.',
      descriptionEn: 'Sheltered bay in Terceira with consistent waves. Long beach with light sand. Unique scenery of the Central Azores.',
      facilities: ['Estacionamento', 'Restaurantes', 'WC'],
      hazards: ['Correntes moderadas']
    },
  {
      id: 'santa-catarina-terceira', slug: 'santa-catarina-terceira', name: 'Santa Catarina', nameEn: 'Santa Catarina',
      region: 'Terceira', regionEn: 'Terceira', lat: 38.683, lon: -27.218,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, NE', bestSwell: 'W, NW',
      description: 'Reef break exposto e consistente. O mais popular da Terceira. Ondas longas e tubulares sobre fundo de rocha.',
      descriptionEn: 'Exposed and consistent reef break. The most popular in Terceira. Long and tubular waves over rock bottom.',
      facilities: ['Estacionamento', 'WC'],
      hazards: ['Rochas afiadas', 'Acesso difícil']
    },
  {
      id: 'parede', slug: 'parede', name: 'Parede', nameEn: 'Parede',
      region: 'Cascais', regionEn: 'Cascais', lat: 38.680, lon: -9.350,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Praia rochosa entre Carcavelos e São Pedro. Ondas rápidas e tubulares em dias de swell. Palco de competições de bodyboard.',
      descriptionEn: 'Rocky beach between Carcavelos and Sao Pedro. Fast and tubular waves on swell days. Host of bodyboarding competitions.',
      facilities: ['Estacionamento', 'Restaurante', 'WC'],
      hazards: ['Rochas', 'Ondas rápidas'],
      compatibleSports: ['surf', 'bodyboard']
    },
  {
      id: 'carcavelos', slug: 'carcavelos', name: 'Carcavelos', nameEn: 'Carcavelos',
      region: 'Cascais', regionEn: 'Cascais', lat: 38.679, lon: -9.335,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'N, NE', bestSwell: 'W, NW',
      description: 'O beach break mais famoso de Lisboa. Ondas de classe mundial ao pé do Forte de São Julião. Multidão de surfistas de qualidade.',
      descriptionEn: 'The most famous beach break in Lisbon. World-class waves next to Forte de São Julião. Crowd of quality surfers.',
      facilities: ['Estacionamento', 'Escola surf', 'Restaurantes', 'Comboio', 'WC'],
      hazards: ['Multidão extrema', 'Correntes']
    },
  {
      id: 'nova-vaga', slug: 'nova-vaga', name: 'Nova Vaga (Costa da Caparica)', nameEn: 'Nova Vaga (Costa da Caparica)',
      region: 'Costa da Caparica', regionEn: 'Costa da Caparica', lat: 38.660, lon: -9.240,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Um dos picos mais consistentes da Costa da Caparica. Múltiplos peaks com ondas de qualidade. Muito procurada por surfistas de Lisboa.',
      descriptionEn: 'One of the most consistent peaks at Costa da Caparica. Multiple peaks with quality waves. Very popular among Lisbon surfers.',
      facilities: ['Estacionamento', 'Escola surf', 'Restaurante', 'WC'],
      hazards: ['Correntes', 'Multidão'],
      compatibleSports: ['surf', 'bodyboard']
    },
  {
      id: 'sao-joao-caparica', slug: 'sao-joao-caparica', name: 'São João da Caparica', nameEn: 'Sao Joao da Caparica',
      region: 'Costa da Caparica', regionEn: 'Costa da Caparica', lat: 38.650, lon: -9.230,
      coastOrientation: 270,
      type: 'surf', difficulty: 'beginner', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Praia mais tranquila da Costa da Caparica. Ondas suaves ideais para aprender. Menos crowd que as praias centrais. Perfeita para famílias e iniciantes.',
      descriptionEn: 'Quieter beach at Costa da Caparica. Gentle waves ideal for learning. Less crowded than central beaches. Perfect for families and beginners.',
      facilities: ['Estacionamento', 'Escola surf', 'Restaurantes', 'WC'],
      hazards: ['Correntes moderadas'],
      compatibleSports: ['surf', 'bodyboard', 'sup'],
      blueFlag: true
    },
  {
      id: 'costa-caparica', slug: 'costa-caparica', name: 'Costa da Caparica', nameEn: 'Costa da Caparica',
      region: 'Almada', regionEn: 'Almada', lat: 38.645, lon: -9.236,
      coastOrientation: 270,
      type: 'surf', difficulty: 'beginner', bestWind: 'E, SE', bestSwell: 'W, SW',
      description: '10km de beach breaks perfeitos para aprender. Várias praias: Dragão Vermelho, CDS, Rainha. A 20 min de Lisboa.',
      descriptionEn: '10km of perfect beach breaks to learn. Multiple beaches: Dragão Vermelho, CDS, Rainha. 20 min from Lisbon.',
      facilities: ['Estacionamento', 'Escolas surf', 'Restaurantes', 'WC'],
      hazards: ['Correntes em alguns picos']
    },
  {
      id: 'fonte-telha', slug: 'fonte-telha', name: 'Fonte da Telha', nameEn: 'Fonte da Telha',
      region: 'Almada', regionEn: 'Almada', lat: 38.580, lon: -9.212,
      coastOrientation: 270,
      type: 'kitesurf', difficulty: 'beginner', bestWind: 'NW, N', bestSwell: 'SW',
      description: 'Praia de areia com ondas pequenas. Perfeito para iniciantes de kitesurf. Vento térmico de Nortada no verão. Pouca multidão!',
      descriptionEn: 'Sand beach with small waves. Perfect for beginner kitesurfers. Thermal Nortada wind in summer. Low crowd!',
      facilities: ['Estacionamento', 'Escola kite', 'WC'],
      hazards: ['Falésias no fundo — usar vento sideshore']
    },
  {
      id: 'almoxarife', slug: 'almoxarife', name: 'Praia do Almoxarife', nameEn: 'Praia do Almoxarife',
      region: 'Faial', regionEn: 'Faial', lat: 38.533, lon: -28.633,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'N, NW',
      description: 'Breaks rochosos na costa leste do Faial. Recebe swell do norte e sul. Vistas para o Pico.',
      descriptionEn: 'Rocky breaks on the east coast of Faial. Takes north and south swells. Views of Pico.',
      facilities: ['Estacionamento', 'WC'],
      hazards: ['Rochas', 'Pouco profundo']
    },
  {
      id: 'lagoa-albufeira', slug: 'lagoa-albufeira', name: 'Lagoa de Albufeira', nameEn: 'Albufeira Lagoon',
      region: 'Sesimbra', regionEn: 'Sesimbra', lat: 38.501, lon: -9.140,
      coastOrientation: 270,
      type: 'kitesurf', difficulty: 'beginner', bestWind: 'NW, N', bestSwell: 'SW',
      description: 'Lagoa separada do oceano por um banco de areia. Água plana até à cintura — paraíso para iniciantes. Nortada consistente.',
      descriptionEn: 'Lagoon separated from the ocean by a sand bar. Chest-high flat water — paradise for beginners. Consistent Nortada.',
      facilities: ['Estacionamento', 'Escola kite', 'Aluguer', 'WC'],
      hazards: ['Maré alta pode subir a lagoa']
    },
  {
      id: 'foil-lagoa-albufeira', slug: 'foil-lagoa-albufeira', name: 'Lagoa de Albufeira - Foil', nameEn: 'Albufeira Lagoon - Foil',
      region: 'Sesimbra', regionEn: 'Sesimbra', lat: 38.501, lon: -9.140,
      coastOrientation: 270,
      type: 'foil', difficulty: 'beginner', bestWind: 'NW, N', bestSwell: 'Lagoa',
      description: 'Paraíso do foil! Água plana até à cintura, vento térmico consistente. Perfeito para aprender wing foil e kite foil. Sem ondas, sem stress.',
      descriptionEn: 'Foil paradise! Chest-high flat water, consistent thermal wind. Perfect for learning wing foil and kite foil. No waves, no stress.',
      facilities: ['Estacionamento', 'Escola foil', 'Aluguer', 'WC'],
      hazards: ['Maré alta pode subir a lagoa', 'Outros riders']
    },
  {
      id: 'alqueva', slug: 'alqueva', name: 'Alqueva', nameEn: 'Alqueva',
      region: 'Alentejo', regionEn: 'Alentejo', lat: 38.200, lon: -7.500,
      coastOrientation: 270,
      type: 'wakeboard', difficulty: 'all', bestWind: 'Vário', bestSwell: 'Lagoa',
      description: 'Maior lago artificial da Europa. Wakeboard e waterski com Mastercraft. Clima estável e água calma o ano todo.',
      descriptionEn: 'Largest artificial lake in Europe. Wakeboard and waterski with Mastercraft. Stable climate and calm water all year round.',
      facilities: ['Estacionamento', 'Escola wake', 'Aluguer', 'Restaurante'],
      hazards: ['Barcos de pesca']
    },
  {
      id: 'sao-torpes', slug: 'sao-torpes', name: 'São Torpes', nameEn: 'Sao Torpes',
      region: 'Alentejo', regionEn: 'Alentejo', lat: 37.922, lon: -8.806,
      coastOrientation: 270,
      type: 'surf', difficulty: 'beginner', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Spot único — antiga central térmica aquece a água! Surf de inverno com wetsuit mais fino. Beach break longo e acessível.',
      descriptionEn: 'Unique spot — old power station warms the water! Winter surfing with thinner wetsuit. Long and accessible beach break.',
      facilities: ['Estacionamento', 'Restaurante', 'WC'],
      hazards: ['Estruturas industriais no fundo']
    },
  {
      id: 'mosteiros', slug: 'mosteiros', name: 'Mosteiros', nameEn: 'Mosteiros',
      region: 'São Miguel', regionEn: 'Sao Miguel', lat: 37.890, lon: -25.823,
      coastOrientation: 270,
      type: 'surf', difficulty: 'advanced', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Point break direito com ondas longas sobre rocha vulcânica. Os ilhéus escuros criam um cenário épico ao pôr do sol.',
      descriptionEn: 'Right-hand point break with long waves over volcanic rock. The dark islets create an epic sunset scenery.',
      facilities: ['Estacionamento', 'Restaurante', 'WC'],
      hazards: ['Rocha vulcânica rasa', 'Acesso difícil']
    },
  {
      id: 'porto-covo', slug: 'porto-covo', name: 'Porto Covo', nameEn: 'Porto Covo',
      region: 'Alentejo', regionEn: 'Alentejo', lat: 37.852, lon: -8.790,
      coastOrientation: 270,
      type: 'surf', difficulty: 'beginner', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Vila piscatória típica com praias cristalinas. Praia Grande com ondas perfeitas para longboarders. Várias enseadas secretas.',
      descriptionEn: 'Typical fishing village with crystal clear beaches. Praia Grande with perfect waves for longboarders. Several secret coves.',
      facilities: ['Estacionamento', 'Restaurantes', 'WC'],
      hazards: ['Acesso por trilhos']
    },
  {
      id: 'monte-verde', slug: 'monte-verde', name: 'Monte Verde', nameEn: 'Monte Verde',
      region: 'São Miguel', regionEn: 'Sao Miguel', lat: 37.829, lon: -25.653,
      coastOrientation: 0,
      type: 'surf', difficulty: 'intermediate', bestWind: 'S, SE', bestSwell: 'NW, W',
      description: 'Beach break versátil que funciona com qualquer swell. Ondas poderosas em dias grandes. Fácil acesso pela cidade de Ribeira Grande.',
      descriptionEn: 'Versatile beach break that works with any swell. Powerful waves on big days. Easy access from Ribeira Grande town.',
      facilities: ['Estacionamento', 'Café', 'WC'],
      hazards: ['Correntes', 'Ondas pesadas']
    },
  {
      id: 'santa-barbara', slug: 'santa-barbara', name: 'Santa Bárbara', nameEn: 'Santa Barbara',
      region: 'São Miguel', regionEn: 'Sao Miguel', lat: 37.821, lon: -25.698,
      coastOrientation: 0,
      type: 'surf', difficulty: 'intermediate', bestWind: 'S, SE', bestSwell: 'N, NW',
      description: 'Paraíso dos surfistas nos Açores. Ondas potentes com cenário vulcânico único. Competições internacionais. Areia negra vulcânica.',
      descriptionEn: 'Surfers paradise in the Azores. Powerful waves with unique volcanic scenery. International competitions. Black volcanic sand.',
      facilities: ['Estacionamento', 'Café', 'Escola surf', 'WC'],
      hazards: ['Rochas vulcânicas', 'Multidão em eventos']
    },
  {
      id: 'malhao', slug: 'malhao', name: 'Malhão', nameEn: 'Malhao',
      region: 'Alentejo', regionEn: 'Alentejo', lat: 37.775, lon: -8.775,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Beach break versátil de 2km com múltiplos picos. Varia de slab overhead a ondas de joelho. Escolas de surf locais.',
      descriptionEn: 'Versatile 2km beach break with multiple peaks. Varies from overhead slab to knee-high waves. Local surf schools.',
      facilities: ['Estacionamento', 'Escola surf', 'WC'],
      hazards: ['Multidão', 'Correntes']
    },
  {
      id: 'milicias', slug: 'milicias', name: 'Milícias', nameEn: 'Milicias',
      region: 'São Miguel', regionEn: 'Sao Miguel', lat: 37.738, lon: -25.636,
      coastOrientation: 180,
      type: 'surf', difficulty: 'beginner', bestWind: 'N, NE', bestSwell: 'S, SW',
      description: 'Praia urbana perto de Ponta Delgada. Areia negra vulcânica com múltiplos picos. Consistente com swell do sul.',
      descriptionEn: 'Urban beach near Ponta Delgada. Black volcanic sand with multiple peaks. Consistent with south swell.',
      facilities: ['Estacionamento', 'Escola surf', 'Restaurantes', 'WC'],
      hazards: ['Multidão', 'Surf schools']
    },
  {
      id: 'vila-nova-milfontes', slug: 'vila-nova-milfontes', name: 'Vila Nova de Milfontes', nameEn: 'Vila Nova de Milfontes',
      region: 'Alentejo', regionEn: 'Alentejo', lat: 37.723, lon: -8.783,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, NE', bestSwell: 'W, NW',
      description: 'Vila charmosa na foz do rio Mira. Múltiplos beach breaks: Malhão, Aivados, Furnas. Costa Vicentina selvagem.',
      descriptionEn: 'Charming village at the mouth of the Mira River. Multiple beach breaks: Malhao, Aivados, Furnas. Wild Vicentina Coast.',
      facilities: ['Estacionamento', 'Escola surf', 'Restaurantes', 'Alojamento', 'WC'],
      hazards: ['Correntes']
    },
  {
      id: 'alteirinhos', slug: 'alteirinhos', name: 'Alteirinhos', nameEn: 'Alteirinhos',
      region: 'Zambujeira do Mar', regionEn: 'Zambujeira do Mar', lat: 37.650, lon: -8.780,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Praia selvagem ao sul da Zambujeira do Mar. Acesso por escadaria na falésia. Areia fina, falésias altas e mar transparente. Perfeita para quem quer fugir das multidões.',
      descriptionEn: 'Wild beach south of Zambujeira do Mar. Access by staircase in the cliff. Fine sand, high cliffs and transparent sea. Perfect for those who want to escape the crowds.',
      facilities: ['Estacionamento'],
      hazards: ['Escadaria íngreme', 'Sem vigilância'],
      compatibleSports: ['surf', 'bodyboard']
    },
  {
      id: 'agua-alto', slug: 'agua-alto', name: "Água d'Alto", nameEn: 'Agua de Alto',
      region: 'São Miguel', regionEn: 'Sao Miguel', lat: 37.714, lon: -25.472,
      coastOrientation: 180,
      type: 'surf', difficulty: 'beginner', bestWind: 'N, NE', bestSwell: 'S, SE',
      description: 'Alternativa perfeita para fugir da multidão de Milícias. Beach break com fundo misto. Esquerda longa perto do hotel.',
      descriptionEn: 'Perfect alternative to escape the Milicias crowd. Beach break with mixed bottom. Long left near the hotel.',
      facilities: ['Estacionamento', 'Hotel', 'WC'],
      hazards: ['Rochas no fundo']
    },
  {
      id: 'zambujeira', slug: 'zambujeira', name: 'Zambujeira do Mar', nameEn: 'Zambujeira do Mar',
      region: 'Alentejo', regionEn: 'Alentejo', lat: 37.527, lon: -8.785,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, NE', bestSwell: 'W, NW',
      description: 'Vila postal nas falésias com beach break potente. Direita pesada junto às falésias. Festival MEO Sudoeste nas proximidades.',
      descriptionEn: 'Postcard village on cliffs with powerful beach break. Heavy right near the cliffs. MEO Sudoeste festival nearby.',
      facilities: ['Estacionamento', 'Restaurante', 'WC'],
      hazards: ['Ondas pesadas', 'Locals']
    },
  {
      id: 'odeceixe', slug: 'odeceixe', name: 'Odeceixe', nameEn: 'Odeceixe',
      region: 'Alentejo', regionEn: 'Alentejo', lat: 37.440, lon: -8.800,
      coastOrientation: 270,
      type: 'surf', difficulty: 'beginner', bestWind: 'N, NE', bestSwell: 'S, SW',
      description: 'Praia única onde o rio encontra o mar. Perfeita para SUP e iniciantes de surf. Natureza intocada.',
      descriptionEn: 'Unique beach where the river meets the sea. Perfect for SUP and beginner surfers. Untouched nature.',
      facilities: ['Estacionamento', 'Restaurante', 'WC'],
      hazards: ['Correntes de maré']
    },
  {
      id: 'amoreira', slug: 'amoreira', name: 'Praia da Amoreira', nameEn: 'Amoreira Beach',
      region: 'Aljezur', regionEn: 'Aljezur', lat: 37.350, lon: -8.850,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, NE', bestSwell: 'W, NW',
      description: 'Praia deslumbrante onde o rio Aljezur encontra o Atlântico. Dunas, falésias e uma lagoa perfeita para SUP. Ondas consistentes com múltiplos picos. Um dos spots mais bonitos da Costa Vicentina.',
      descriptionEn: 'Stunning beach where the Aljezur river meets the Atlantic. Dunes, cliffs and a perfect lagoon for SUP. Consistent waves with multiple peaks. One of the most beautiful spots on the Vicentina Coast.',
      compatibleSports: ['surf', 'kitesurf', 'sup'],
      blueFlag: true,
      facilities: ['Estacionamento', 'Restaurante', 'WC'],
      hazards: ['Correntes na foz do rio', 'Rochas']
    },
  {
      id: 'monte-clerigo', slug: 'monte-clerigo', name: 'Monte Clérigo', nameEn: 'Monte Clerigo',
      region: 'Aljezur', regionEn: 'Aljezur', lat: 37.340, lon: -8.860,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, NE', bestSwell: 'W, NW',
      description: 'Praia de vila piscatória com ambiente boémio. Picos shiftantes que quando alinham oferecem ondas divertidas. Ótima para famílias e surfistas em evolução.',
      descriptionEn: 'Fishing village beach with bohemian atmosphere. Shifty peaks that when aligned offer fun waves. Great for families and evolving surfers.',
      facilities: ['Estacionamento', 'Restaurantes', 'WC'],
      hazards: ['Rochas na maré baixa', 'Bancos de areia mutáveis'],
      compatibleSports: ['surf', 'bodyboard']
    },
  {
      id: 'arrifana', slug: 'arrifana', name: 'Arrifana', nameEn: 'Arrifana',
      region: 'Algarve', regionEn: 'Algarve', lat: 37.294, lon: -8.864,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Baía protegida com ondas consistentes para todos os níveis. Fundo misto de areia e rocha. Cenário deslumbrante.',
      descriptionEn: 'Protected bay with consistent waves for all levels. Mixed sand and rock bottom. Stunning scenery.',
      facilities: ['Estacionamento', 'Restaurantes', 'Escola surf', 'WC'],
      hazards: ['Rochas', 'Correntes na saída']
    },
  {
      id: 'vale-figueiras', slug: 'vale-figueiras', name: 'Vale Figueiras', nameEn: 'Vale Figueiras',
      region: 'Aljezur', regionEn: 'Aljezur', lat: 37.250, lon: -8.850,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, NE', bestSwell: 'W, NW',
      description: 'Praia selvagem no Parque Natural do Sudoeste Alentejano. Ondas para todos os níveis dependendo das condições. Acesso por estrada de terra. Isolamento total.',
      descriptionEn: 'Wild beach in the Southwest Alentejo Natural Park. Waves for all levels depending on conditions. Dirt road access. Total isolation.',
      facilities: ['Estacionamento'],
      hazards: ['Sem vigilância', 'Acesso difícil'],
      compatibleSports: ['surf', 'bodyboard']
    },
  {
      id: 'amado', slug: 'amado', name: 'Praia do Amado', nameEn: 'Amado Beach',
      region: 'Carrapateira', regionEn: 'Carrapateira', lat: 37.180, lon: -8.900,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, NE', bestSwell: 'W, NW',
      description: 'Um dos spots mais consistentes e famosos do Algarve. Três picos principais visíveis do miradouro. Ondas potentes com muitos surfistas de várias nacionalidades no verão.',
      descriptionEn: 'One of the most consistent and famous spots in the Algarve. Three main peaks visible from the viewpoint. Powerful waves with many surfers of various nationalities in summer.',
      compatibleSports: ['surf', 'bodyboard', 'sup'],
      blueFlag: true,
      facilities: ['Estacionamento', 'Escolas surf', 'Restaurantes', 'WC'],
      hazards: ['Correntes', 'Ondas potentes', 'Multidão no verão']
    },
  {
      id: 'bordeira', slug: 'bordeira', name: 'Praia da Bordeira', nameEn: 'Bordeira Beach',
      region: 'Carrapateira', regionEn: 'Carrapateira', lat: 37.150, lon: -8.880,
      coastOrientation: 270,
      type: 'kitesurf', difficulty: 'advanced', bestWind: 'N, NW', bestSwell: 'W, NW',
      description: 'Ondas enormes no inverno, lagoon plana no verão. Um dos spots mais versáteis do Algarve para kitesurf e surf. Vento cross-onshore consistente.',
      descriptionEn: 'Huge waves in winter, flat lagoon in summer. One of the most versatile spots in the Algarve for kitesurfing and surfing. Consistent cross-onshore wind.',
      facilities: ['Estacionamento'],
      hazards: ['Ondas gigantes no inverno', 'Correntes'],
      compatibleSports: ['kitesurf', 'surf', 'bodyboard']
    },
  {
      id: 'barriga', slug: 'barriga', name: 'Barriga', nameEn: 'Barriga',
      region: 'Vila do Bispo', regionEn: 'Vila do Bispo', lat: 37.100, lon: -8.930,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Praia isolada a norte da Cordoama. Ondas de qualidade quando os bancos alinham. Pouco crowd e ambiente natural preservado. Acesso a pé na maré baixa.',
      descriptionEn: 'Isolated beach north of Cordoama. Quality waves when the banks align. Low crowd and preserved natural environment. Foot access at low tide.',
      facilities: [],
      hazards: ['Sem infraestruturas', 'Acesso difícil', 'Correntes'],
      compatibleSports: ['surf', 'bodyboard']
    },
  {
      id: 'castelejo', slug: 'castelejo', name: 'Castelejo', nameEn: 'Castelejo',
      region: 'Vila do Bispo', regionEn: 'Vila do Bispo', lat: 37.090, lon: -8.960,
      coastOrientation: 270,
      type: 'surf', difficulty: 'advanced', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Praia selvagem com ondas potentes e tubulares. Spot avançado com fundo de areia e rochas. Cenário dramático com falésias negras.',
      descriptionEn: 'Wild beach with powerful and tubular waves. Advanced spot with sand and rock bottom. Dramatic scenery with black cliffs.',
      facilities: ['Estacionamento'],
      hazards: ['Rochas', 'Ondas potentes', 'Correntes fortes'],
      compatibleSports: ['surf', 'bodyboard']
    },
  {
      id: 'luz', slug: 'luz', name: 'Praia da Luz', nameEn: 'Praia da Luz',
      region: 'Lagos', regionEn: 'Lagos', lat: 37.087, lon: -8.731,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Praia familiar que esconde um reef break de qualidade junto à Rocha Negra. Direitas perfeitas com a maré e swell certos. Pouco conhecida fora da comunidade local.',
      descriptionEn: 'Family beach that hides a quality reef break near Rocha Negra. Perfect rights with the right tide and swell. Little known outside the local community.',
      facilities: ['Estacionamento', 'Restaurantes', 'Alojamento', 'WC'],
      hazards: ['Rochas', 'Correntes'],
      compatibleSports: ['surf', 'bodyboard'],
      blueFlag: true
    },
  {
      id: 'burgau', slug: 'burgau', name: 'Burgau', nameEn: 'Burgau',
      region: 'Vila do Bispo', regionEn: 'Vila do Bispo', lat: 37.070, lon: -8.780,
      coastOrientation: 180,
      type: 'surf', difficulty: 'beginner', bestWind: 'N, NW', bestSwell: 'S, SW',
      description: 'Aldeia piscatória autêntica com point break nas duas pontas da baía. Ambiente familiar e água cristalina. Quando funciona, transforma-se numa pequena piscina de ondas.',
      descriptionEn: 'Authentic fishing village with point break on both ends of the bay. Family atmosphere and crystal clear water. When it works, it transforms into a small wave pool.',
      facilities: ['Estacionamento', 'Restaurantes', 'WC'],
      hazards: ['Rochas nas pontas'],
      compatibleSports: ['surf', 'bodyboard', 'sup']
    },
  {
      id: 'salema', slug: 'salema', name: 'Salema', nameEn: 'Salema',
      region: 'Vila do Bispo', regionEn: 'Vila do Bispo', lat: 37.065, lon: -8.824,
      coastOrientation: 180,
      type: 'surf', difficulty: 'beginner', bestWind: 'N, NW', bestSwell: 'S, SW',
      description: 'Praia de vila piscatória no coração do Algarve. Ondas suaves ideais para iniciantes e longboarders. Água cristalina e ambiente tranquilo.',
      descriptionEn: 'Fishing village beach in the heart of the Algarve. Gentle waves ideal for beginners and longboarders. Crystal clear water and tranquil atmosphere.',
      facilities: ['Estacionamento', 'Restaurantes', 'Alojamento', 'WC'],
      hazards: ['Rochas submersas'],
      compatibleSports: ['surf', 'sup'],
      blueFlag: true
    },
  {
      id: 'cordoama', slug: 'cordoama', name: 'Cordoama', nameEn: 'Cordoama',
      region: 'Vila do Bispo', regionEn: 'Vila do Bispo', lat: 37.050, lon: -8.950,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Spot flanqueado por falésias imponentes. Um dos mais consistentes da região, palco do circuito mundial WQS. Bancos de areia bem colocados. Menos massificado que o Amado.',
      descriptionEn: 'Spot flanked by imposing cliffs. One of the most consistent in the region, host of the WQS world circuit. Well-placed sandbanks. Less crowded than Amado.',
      facilities: ['Estacionamento', 'Restaurante'],
      hazards: ['Rochas', 'Correntes', 'Exposição ao vento'],
      compatibleSports: ['surf', 'bodyboard']
    },
  {
      id: 'ferragudo', slug: 'ferragudo', name: 'Praia Grande de Ferragudo', nameEn: 'Praia Grande de Ferragudo',
      region: 'Lagoa', regionEn: 'Lagoa', lat: 37.120, lon: -8.520,
      coastOrientation: 180,
      type: 'windsurf', difficulty: 'intermediate', bestWind: 'SE, E', bestSwell: 'S, SW',
      description: 'Excelente spot de wing foil e windsurf no inverno com o vento Levante (SE). Ondas rolantes na baía. Cenário pitoresco com o castelo de Ferragudo ao fundo.',
      descriptionEn: 'Excellent wing foiling and windsurfing spot in winter with Levante wind (SE). Rolling waves in the bay. Picturesque scenery with Ferragudo castle in the background.',
      facilities: ['Estacionamento', 'Restaurantes', 'WC'],
      hazards: ['Correntes na foz do rio', 'Bancos de areia'],
      compatibleSports: ['windsurf', 'foil', 'kitesurf']
    },
  {
      id: 'vila-real-santo-antonio', slug: 'vila-real-santo-antonio', name: 'Vila Real de Santo António', nameEn: 'Vila Real de Santo Antonio',
      region: 'Algarve', regionEn: 'Algarve', lat: 37.200, lon: -7.418,
      coastOrientation: 180,
      type: 'kitesurf', difficulty: 'beginner', bestWind: 'E, SE', bestSwell: 'Ria Formosa',
      description: 'Água plana na Ria Formosa com vento de leste térmico consistente. Um dos spots mais fiáveis do Algarve para kitesurf. Praia extensa e segura.',
      descriptionEn: 'Flat water in Ria Formosa with consistent east thermal wind. One of the most reliable spots in the Algarve for kitesurfing. Long and safe beach.',
      facilities: ['Estacionamento', 'Escolas kite', 'Aluguer', 'Restaurantes', 'WC'],
      hazards: ['Tráfego de barcos na ria']
    },
  {
      id: 'monte-gordo', slug: 'monte-gordo', name: 'Monte Gordo', nameEn: 'Monte Gordo',
      region: 'Algarve', regionEn: 'Algarve', lat: 37.183, lon: -7.450,
      coastOrientation: 180,
      type: 'kitesurf', difficulty: 'beginner', bestWind: 'E, SE', bestSwell: 'S, SE',
      description: 'Praia dourada extensa com água morna e vento de leste épico. Kitesurf perfeito para todos os níveis. Uma das melhores praias do Sotavento.',
      descriptionEn: 'Long golden beach with warm water and epic east wind. Perfect kitesurfing for all levels. One of the best beaches in the Sotavento.',
      facilities: ['Estacionamento', 'Escolas kite', 'Restaurantes', 'WC'],
      hazards: ['Multidão no verão']
    },
  {
      id: 'praia-verde', slug: 'praia-verde', name: 'Praia Verde', nameEn: 'Praia Verde',
      region: 'Algarve', regionEn: 'Algarve', lat: 37.183, lon: -7.500,
      coastOrientation: 180,
      type: 'kitesurf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'S, SE',
      description: 'Praia selvagem entre VRSA e Monte Gordo. Menos crowd, ondas mais organizadas. Kitesurf com vento de leste e ondas de Sotavento. ⚠️ Proibido kitesurf de 1 junho a 30 setembro — usar Altura (a 3km) como alternativa.',
      descriptionEn: 'Wild beach between VRSA and Monte Gordo. Less crowded, more organized waves. Kitesurfing with east wind and Sotavento waves. ⚠️ Kitesurf banned 1 Jun–30 Sep — use Altura (3km away) as alternative.',
      facilities: ['Estacionamento', 'Bar de praia (verão)'],
      hazards: ['Correntes', 'Sem vigilância', 'Kitesurf proibido 1 Jun–30 Sep']
    },
  {
      id: 'altura', slug: 'altura', name: 'Altura (Praia da Alagoa)', nameEn: 'Altura (Alagoa Beach)',
      region: 'Algarve', regionEn: 'Algarve', lat: 37.170, lon: -7.498,
      coastOrientation: 180,
      type: 'kitesurf', difficulty: 'beginner', bestWind: 'E, SE', bestSwell: 'S, SE',
      description: 'Praia extensa em Altura, a 3km de Monte Gordo. Água plana e vento de leste consistente. Alternativa oficial para kitesurf durante a proibição de Verão na Praia Verde (1 junho–30 setembro). Escola de kite no local.',
      descriptionEn: 'Long beach at Altura, 3km from Monte Gordo. Flat water and consistent east wind. Official alternative for kitesurfing during the Praia Verde summer ban (1 Jun–30 Sep). Kite school on site.',
      facilities: ['Estacionamento', 'Escola kite', 'Restaurantes', 'WC'],
      hazards: ['Multidão no verão']
    },
  {
      id: 'praia-rocha', slug: 'praia-rocha', name: 'Praia da Rocha', nameEn: 'Praia da Rocha',
      region: 'Portimão', regionEn: 'Portimão', lat: 37.117, lon: -8.533,
      coastOrientation: 270,
      type: 'multisport', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'SW',
      description: 'Praia de areia com falésias impressionantes. Ondas de inverno para surf. Vento de leste para windsurf e kitesurf no verão.',
      descriptionEn: 'Sand beach with impressive cliffs. Winter waves for surf. East wind for windsurf and kitesurf in summer.',
      facilities: ['Estacionamento', 'Restaurantes', 'WC'],
      hazards: ['Rochas submersas', 'Multidão na época alta']
    },
  {
      id: 'alvor', slug: 'alvor', name: 'Alvor', nameEn: 'Alvor',
      region: 'Algarve', regionEn: 'Algarve', lat: 37.136, lon: -8.594,
      coastOrientation: 180,
      type: 'multisport', difficulty: 'beginner', bestWind: 'W, NW', bestSwell: 'S, SW',
      description: 'Praia extensa com ondas suaves. Ideal para surf iniciante, SUP e famílias. Lagoa de Alvor para kitesurf flat water.',
      descriptionEn: 'Long beach with gentle waves. Ideal for beginner surf, SUP and families. Alvor Lagoon for flat water kitesurf.',
      facilities: ['Estacionamento', 'Restaurantes', 'Aluguer', 'Salva-vidas', 'WC'],
      hazards: ['Rochas na extremidade sul']
    },
  {
      id: 'foil-alvor', slug: 'foil-alvor', name: 'Alvor - Foil', nameEn: 'Alvor - Foil',
      region: 'Algarve', regionEn: 'Algarve', lat: 37.136, lon: -8.594,
      coastOrientation: 270,
      type: 'foil', difficulty: 'intermediate', bestWind: 'W, NW', bestSwell: 'Lagoa',
      description: 'Lagoa de Alvor é o spot secreto de foil do Algarve. Água plana com vento térmico. Wing foil e kite foil em condições perfeitas.',
      descriptionEn: 'Alvor Lagoon is the secret foil spot of the Algarve. Flat water with thermal wind. Wing foil and kite foil in perfect conditions.',
      facilities: ['Estacionamento', 'Escola foil', 'Aluguer', 'WC'],
      hazards: ['Rochas na extremidade sul', 'Maré']
    },
  {
      id: 'lagos', slug: 'lagos', name: 'Meia Praia', nameEn: 'Meia Praia',
      region: 'Lagos', regionEn: 'Lagos', lat: 37.115, lon: -8.653,
      coastOrientation: 180,
      type: 'kitesurf', difficulty: 'beginner', bestWind: 'NW, N', bestSwell: 'S',
      description: 'Praia extensa de 4km com vento side-shore. Escola de kitesurf e windsurf no centro.',
      descriptionEn: '4km long beach with side-shore wind. Kitesurf and windsurf school in the center.',
      facilities: ['Estacionamento', 'Escolas', 'Aluguer', 'Restaurantes'],
      hazards: ['Tráfego na época alta']
    },
  {
      id: 'lagos-wakepark', slug: 'lagos-wakepark', name: 'Lagos Wake Park', nameEn: 'Lagos Wake Park',
      region: 'Algarve', regionEn: 'Algarve', lat: 37.100, lon: -8.670,
      coastOrientation: 270,
      type: 'wakeboard', difficulty: 'all', bestWind: 'Vário', bestSwell: 'Lagoa',
      description: 'Cable park 2.0 na salina de Lagos. Rampas, rails, kickers e sliders. Mastercraft X-23 para wake boat. Campo completo!',
      descriptionEn: '2.0 cable park on Lagos salt flat. Ramps, rails, kickers and sliders. Mastercraft X-23 for wake boat. Complete park!',
      facilities: ['Estacionamento', 'Cable 2.0', 'Wake Boat', 'Escola', 'Alojamento'],
      hazards: ['Outros riders']
    },
  {
      id: 'beliche', slug: 'beliche', name: 'Praia do Beliche', nameEn: 'Beliche Beach',
      region: 'Sagres', regionEn: 'Sagres', lat: 37.030, lon: -8.970,
      coastOrientation: 270,
      type: 'surf', difficulty: 'advanced', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Praia virada a oeste com ondas potentes. Acesso por escadaria na falésia. Beach break épico em dias grandes.',
      descriptionEn: 'West-facing beach with powerful waves. Access by staircase on the cliff. Epic beach break on big days.',
      facilities: ['Estacionamento limitado', 'WC'],
      hazards: ['Acesso difícil', 'Correntes fortes', 'Rochas']
    },
  {
      id: 'martinhal', slug: 'martinhal', name: 'Martinhal', nameEn: 'Martinhal',
      region: 'Sagres', regionEn: 'Sagres', lat: 37.025, lon: -8.935,
      coastOrientation: 270,
      type: 'windsurf', difficulty: 'intermediate', bestWind: 'N, NW', bestSwell: 'SW',
      description: 'Centro internacional de windsurf. Água plana à tarde com vento térmico. Escola com equipamento de qualidade.',
      descriptionEn: 'International windsurf center. Flat water in the afternoon with thermal wind. School with quality equipment.',
      facilities: ['Estacionamento', 'Escola windsurf', 'Aluguer', 'Restaurante', 'WC'],
      hazards: ['Vento pode desligar de repente']
    },
  {
      id: 'barrinha-faro', slug: 'barrinha-faro', name: 'Barrinha de Faro', nameEn: 'Barrinha de Faro',
      region: 'Algarve', regionEn: 'Algarve', lat: 37.016, lon: -7.933,
      coastOrientation: 180,
      type: 'kitesurf', difficulty: 'beginner', bestWind: 'E, SE', bestSwell: 'Ria Formosa',
      description: 'Lagoa da Ria Formosa com água plana e vento de leste. Spot perfeito para iniciantes e freestyle. Barra de acesso com barco típico.',
      descriptionEn: 'Ria Formosa lagoon with flat water and east wind. Perfect spot for beginners and freestyle. Access via traditional boat.',
      facilities: ['Estacionamento', 'Barco-táxi', 'Escolas kite', 'Restaurantes'],
      hazards: ['Tráfego de barcos', 'Maré']
    },
  {
      id: 'fuseta', slug: 'fuseta', name: 'Fuseta', nameEn: 'Fuseta',
      region: 'Olhão', regionEn: 'Olhao', lat: 37.050, lon: -7.750,
      coastOrientation: 180,
      type: 'kitesurf', difficulty: 'beginner', bestWind: 'SW, W', bestSwell: 'Lagoa',
      description: 'Laguna calma na Ria Formosa, alternativa menos concorrida que Alvor. Funciona na maré alta. Vento térmico consistente no verão. Água quente e plana perfeita para iniciantes.',
      descriptionEn: 'Calm lagoon in Ria Formosa, less crowded alternative to Alvor. Works at high tide. Consistent thermal wind in summer. Warm and flat water perfect for beginners.',
      facilities: ['Estacionamento', 'Escola kite', 'WC'],
      hazards: ['Bancos de areia na maré baixa', 'Balsa de barcos'],
      compatibleSports: ['kitesurf', 'foil', 'sup']
    },
  {
      id: 'ilha-faro', slug: 'ilha-faro', name: 'Ilha de Faro', nameEn: 'Faro Island',
      region: 'Faro', regionEn: 'Faro', lat: 36.980, lon: -7.980,
      coastOrientation: 180,
      type: 'kitesurf', difficulty: 'intermediate', bestWind: 'NW, N', bestSwell: 'Lagoa',
      description: 'Ilha na Ria Formosa com lagoon de água plana e praia oceânica. Kitesurf na lagoon, SUP na calma do estuário. Flamingos e natureza intocada.',
      descriptionEn: 'Island in Ria Formosa with flat water lagoon and ocean beach. Kitesurfing in the lagoon, SUP in the calm estuary. Flamingos and untouched nature.',
      facilities: ['Estacionamento', 'Barco para a ilha', 'WC'],
      hazards: ['Corredores de barcos', 'Bancos de areia'],
      compatibleSports: ['kitesurf', 'sup']
    },
  {
      id: 'ilha-tavira', slug: 'ilha-tavira', name: 'Ilha de Tavira', nameEn: 'Tavira Island',
      region: 'Tavira', regionEn: 'Tavira', lat: 37.120, lon: -7.650,
      coastOrientation: 180,
      type: 'kitesurf', difficulty: 'intermediate', bestWind: 'NW, N', bestSwell: 'Lagoa',
      description: '11km de duna com praia oceânica e lagoon. Ondas suaves na praia e água plana na Ria Formosa. Acessível de barco. Um dos melhores spots do Algarve oriental.',
      descriptionEn: '11km of dune with ocean beach and lagoon. Gentle waves on the beach and flat water in Ria Formosa. Accessible by boat. One of the best spots in eastern Algarve.',
      facilities: ['Barco para a ilha', 'Restaurantes', 'WC'],
      hazards: ['Acesso limitado', 'Correntes na foz'],
      compatibleSports: ['kitesurf', 'surf', 'sup']
    },
  {
      id: 'cabanas-tavira', slug: 'cabanas-tavira', name: 'Cabanas de Tavira', nameEn: 'Cabanas de Tavira',
      region: 'Tavira', regionEn: 'Tavira', lat: 37.130, lon: -7.600,
      coastOrientation: 180,
      type: 'kitesurf', difficulty: 'beginner', bestWind: 'NW, N', bestSwell: 'Lagoa',
      description: 'Praia larga de areia dourada na Ria Formosa. Kitesurf na lagoon no inverno e na ilha o ano todo. Pouco crowd e vento consistente.',
      descriptionEn: 'Wide golden sand beach in Ria Formosa. Kitesurfing in the lagoon in winter and on the island year-round. Low crowd and consistent wind.',
      facilities: ['Estacionamento', 'Barco para a ilha', 'Restaurantes', 'WC'],
      hazards: ['Bancos de areia'],
      compatibleSports: ['kitesurf', 'sup']
    },
  {
      id: 'tonel', slug: 'tonel', name: 'Praia do Tonel', nameEn: 'Tonel Beach',
      region: 'Sagres', regionEn: 'Sagres', lat: 37.010, lon: -8.945,
      coastOrientation: 270,
      type: 'surf', difficulty: 'advanced', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Um dos beach breaks mais consistentes do sul. Ondas nítidas e ocas em frente à falésia. Melhor entre maré baixa e média.',
      descriptionEn: 'One of the most consistent beach breaks in the south. Clean and hollow waves in front of the cliff. Best between low and mid tide.',
      facilities: ['Estacionamento', 'Restaurante', 'WC'],
      hazards: ['Correntes fortes', 'Rochas', 'Multidão']
    },
  {
      id: 'zavial', slug: 'zavial', name: 'Zavial', nameEn: 'Zavial',
      region: 'Sagres', regionEn: 'Sagres', lat: 37.005, lon: -8.925,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'N, NE', bestSwell: 'S, SW',
      description: 'Beach break virado a sul com ondas de qualidade. Menos crowd que Tonel e Beliche. Fundo de areia.',
      descriptionEn: 'South-facing beach break with quality waves. Less crowd than Tonel and Beliche. Sand bottom.',
      facilities: ['Estacionamento', 'WC'],
      hazards: ['Correntes']
    },
  {
      id: 'anjos', slug: 'anjos', name: 'Anjos', nameEn: 'Anjos',
      region: 'Santa Maria', regionEn: 'Santa Maria', lat: 36.967, lon: -25.100,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'S, SW', bestSwell: 'NW, N',
      description: 'Reef break direito exposto na costa noroeste de Santa Maria. Ondas tubulares em dias grandes.',
      descriptionEn: 'Exposed right reef break on the northwest coast of Santa Maria. Tubular waves on big days.',
      facilities: ['Estacionamento limitado', 'WC'],
      hazards: ['Rochas', 'Acesso difícil']
    },
  {
      id: 'ponta-delgada', slug: 'ponta-delgada', name: 'Ponta Delgada (Açores)', nameEn: 'Ponta Delgada (Azores)',
      region: 'Açores', regionEn: 'Azores', lat: 37.741, lon: -25.669,
      coastOrientation: 180,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'São Miguel — ondas potentes no meio do Atlântico. Água cristalina, crowd mínimo. Um paraíso escondido para surfistas aventureiros.',
      descriptionEn: 'São Miguel — powerful waves in the middle of the Atlantic. Crystal clear water, minimal crowd. A hidden paradise for adventurous surfers.',
      facilities: ['Estacionamento', 'Escola surf', 'Restaurantes', 'WC'],
      hazards: ['Ondas irregulares', 'Água fria (17-20°C)']
    },
  {
      id: 'sao-vicente-madeira', slug: 'sao-vicente-madeira', name: 'São Vicente', nameEn: 'Sao Vicente',
      region: 'Madeira', regionEn: 'Madeira', lat: 32.800, lon: -17.033,
      coastOrientation: 270,
      type: 'surf', difficulty: 'beginner', bestWind: 'S, SE', bestSwell: 'N, NW',
      description: 'Norte da ilha com ondas suaves perfeitas para iniciantes. Mar sempre agitado. Escola de surf local.',
      descriptionEn: 'North of the island with soft waves perfect for beginners. Sea always rough. Local surf school.',
      facilities: ['Estacionamento', 'Escola surf', 'WC'],
      hazards: ['Correntes moderadas']
    },
  {
      id: 'porto-da-cruz', slug: 'porto-da-cruz', name: 'Porto da Cruz', nameEn: 'Porto da Cruz',
      region: 'Madeira', regionEn: 'Madeira', lat: 32.767, lon: -16.833,
      coastOrientation: 90,
      type: 'surf', difficulty: 'beginner', bestWind: 'S, SE', bestSwell: 'N, NW',
      description: 'Melhor spot para iniciantes na Madeira. Ondas suaves com areia vulcânica preta. Escolas de surf e ambiente familiar.',
      descriptionEn: 'Best beginner spot in Madeira. Gentle waves with black volcanic sand. Surf schools and family atmosphere.',
      facilities: ['Estacionamento', 'Escolas surf', 'Restaurantes', 'WC'],
      hazards: ['Multidão em dias de evento']
    },
  {
      id: 'paul-mar', slug: 'paul-mar', name: 'Paul do Mar', nameEn: 'Paul do Mar',
      region: 'Madeira', regionEn: 'Madeira', lat: 32.767, lon: -17.233,
      coastOrientation: 270,
      type: 'surf', difficulty: 'advanced', bestWind: 'E, NE', bestSwell: 'W, NW',
      description: 'Ondas tubulares de classe mundial. Aqui foi realizado o World Big Wave Championship 2001. Ondas até 8 metros.',
      descriptionEn: 'World-class barreling waves. The 2001 World Big Wave Championship was held here. Waves up to 8 meters.',
      facilities: ['Estacionamento', 'Restaurante', 'Escola surf'],
      hazards: ['Rochas', 'Ondas gigantescas', 'Correntes']
    },
  {
      id: 'jardim-mar', slug: 'jardim-mar', name: 'Jardim do Mar', nameEn: 'Jardim do Mar',
      region: 'Madeira', regionEn: 'Madeira', lat: 32.750, lon: -17.217,
      coastOrientation: 270,
      type: 'surf', difficulty: 'advanced', bestWind: 'E, NE', bestSwell: 'W, NW',
      description: 'Onda direita lendária da Madeira. Uma das mais pesadas da Europa. Tubos longos sobre reef. Apenas experts.',
      descriptionEn: 'Legendary Madeira right-hand wave. One of the heaviest in Europe. Long tubes over reef. Experts only.',
      facilities: ['Estacionamento limitado', 'Restaurante'],
      hazards: ['Reef raso', 'Acesso por molhe', 'Ondas mortais']
    },
  {
      id: 'ponta-sao-lourenco', slug: 'ponta-sao-lourenco', name: 'Ponta de São Lourenço', nameEn: 'Ponta de Sao Lourenco',
      region: 'Madeira', regionEn: 'Madeira', lat: 32.745, lon: -16.706,
      coastOrientation: 90,
      type: 'surf', difficulty: 'advanced', bestWind: 'N, NE', bestSwell: 'S, SE',
      description: 'Paisagem lunar vulcânica com ondas consistentes. Spot remoto para aventureiros. Águas turquesa e cenário dramático.',
      descriptionEn: 'Lunar volcanic landscape with consistent waves. Remote spot for adventurers. Turquoise waters and dramatic scenery.',
      facilities: ['Estacionamento limitado'],
      hazards: ['Acesso difícil', 'Rochas', 'Sem infraestruturas']
    },
  {
      id: 'ribeira-brava', slug: 'ribeira-brava', name: 'Ribeira Brava', nameEn: 'Ribeira Brava',
      region: 'Madeira', regionEn: 'Madeira', lat: 32.675, lon: -17.063,
      coastOrientation: 90,
      type: 'surf', difficulty: 'intermediate', bestWind: 'N, NE', bestSwell: 'S, SW',
      description: 'Onda de reef break potente na costa sul. Cenário de montanhas verdes. Acesso fácil pela estrada costeira.',
      descriptionEn: 'Powerful reef break wave on the south coast. Green mountain scenery. Easy access by coastal road.',
      facilities: ['Estacionamento', 'Restaurante', 'WC'],
      hazards: ['Rochas', 'Correntes']
    },
  {
      id: 'funchal', slug: 'funchal', name: 'Praia Formosa', nameEn: 'Praia Formosa',
      region: 'Madeira', regionEn: 'Madeira', lat: 32.650, lon: -16.917,
      coastOrientation: 90,
      type: 'kitesurf', difficulty: 'intermediate', bestWind: 'N, NE', bestSwell: 'S',
      description: 'Baía do Funchal com vento térmico. Kitesurf no centro da cidade. Águas quentes e cenário urbano único.',
      descriptionEn: 'Funchal bay with thermal wind. Kitesurf in the city center. Warm waters and unique urban scenery.',
      facilities: ['Estacionamento', 'Escola kite', 'Restaurantes', 'WC'],
      hazards: ['Tráfego de barcos', 'Banhistas']
    },
  {
      id: 'barra-aveiro', slug: 'barra-aveiro', name: 'Praia da Barra (Aveiro)', nameEn: 'Barra Beach (Aveiro)',
      region: 'Aveiro', regionEn: 'Aveiro', lat: 40.638, lon: -8.748,
      coastOrientation: 270,
      type: 'surf', difficulty: 'beginner', bestWind: 'E, NE', bestSwell: 'W, NW',
      description: 'Praia do farol mais alto de Portugal. Ondas suaves e consistentes. Kitesurf na ria adjacente. Um dos spots mais populares de Aveiro.',
      descriptionEn: 'Beach of Portugal\'s tallest lighthouse. Soft and consistent waves. Kitesurf in the adjacent ria. One of the most popular spots in Aveiro.',
      compatibleSports: ['surf', 'kitesurf', 'windsurf'],
      facilities: ['Estacionamento', 'Restaurantes', 'Farol', 'WC'],
      hazards: ['Correntes', 'Multidão no verão']
    },
  {
      id: 'vila-cha', slug: 'vila-cha', name: 'Vila Chã', nameEn: 'Vila Cha',
      region: 'Porto', regionEn: 'Porto', lat: 41.291, lon: -8.739,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Praia selvagem a norte do Porto. Beach break consistente com menos crowd que Matosinhos. Ideal para quem quer fugir da multidão.',
      descriptionEn: 'Wild beach north of Porto. Consistent beach break with less crowd than Matosinhos. Ideal for escaping the crowds.',
      facilities: ['Estacionamento', 'WC'],
      hazards: ['Correntes fortes', 'Acesso íngreme']
    },
  {
      id: 'santa-cruz', slug: 'santa-cruz', name: 'Santa Cruz (Praia Azul)', nameEn: 'Santa Cruz (Praia Azul)',
      region: 'Torres Vedras', regionEn: 'Torres Vedras', lat: 39.139, lon: -9.380,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Praia icónica com ondas consistentes e palco de campeonatos nacionais. Areia dourada e falésias. Kitesurf com vento térmico no verão.',
      descriptionEn: 'Iconic beach with consistent waves, host of national championships. Golden sand and cliffs. Kitesurf with thermal wind in summer.',
      compatibleSports: ['surf', 'kitesurf', 'bodyboard'],
      blueFlag: true,
      facilities: ['Estacionamento', 'Escola surf', 'Restaurantes', 'Alojamento', 'WC'],
      hazards: ['Correntes fortes', 'Multidão no verão', 'Rochas junto ao molhe']
    },
  {
      id: 'consolacao', slug: 'consolacao', name: 'Praia da Consolação', nameEn: 'Consolacao Beach',
      region: 'Peniche', regionEn: 'Peniche', lat: 39.320, lon: -9.367,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Praia entre Peniche e a Lagoa de Óbidos. Beach break potente com múltiplos picos. Menos crowd que Supertubos. Ideal para surfistas intermediários.',
      descriptionEn: 'Beach between Peniche and Obidos Lagoon. Powerful beach break with multiple peaks. Less crowded than Supertubos. Ideal for intermediate surfers.',
      facilities: ['Estacionamento', 'Restaurante', 'WC'],
      hazards: ['Correntes', 'Rochas submersas']
    },
  {
      id: 'areia-branca', slug: 'areia-branca', name: 'Areia Branca', nameEn: 'Areia Branca',
      region: 'Lourinhã', regionEn: 'Lourinha', lat: 39.258, lon: -9.335,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, NE', bestSwell: 'W, NW',
      description: 'Praia turística com ondas consistentes para todos os níveis. Palco de provas do circuito nacional. Golfinhos frequentes.',
      descriptionEn: 'Tourist beach with consistent waves for all levels. Host of national circuit events. Frequent dolphin sightings.',
      blueFlag: true,
      facilities: ['Estacionamento', 'Escola surf', 'Restaurantes', 'Alojamento', 'WC'],
      hazards: ['Multidão no verão', 'Correntes']
    },
  {
      id: 'sao-martinho-porto', slug: 'sao-martinho-porto', name: 'São Martinho do Porto', nameEn: 'Sao Martinho do Porto',
      region: 'Oeste', regionEn: 'West Coast', lat: 39.514, lon: -9.134,
      coastOrientation: 180,
      type: 'kitesurf', difficulty: 'beginner', bestWind: 'N, NW', bestSwell: 'Baía',
      description: 'Baía em forma de concha com águas calmas e vento térmico. Perfeita para aprender kitesurf e windsurf. Água plana protegida.',
      descriptionEn: 'Shell-shaped bay with calm waters and thermal wind. Perfect for learning kitesurf and windsurf. Sheltered flat water.',
      compatibleSports: ['kitesurf', 'windsurf', 'sup'],
      blueFlag: true,
      facilities: ['Estacionamento', 'Escolas kite', 'Restaurantes', 'WC'],
      hazards: ['Tráfego de barcos', 'Maré baixa expõe areia']
    },
  {
      id: 'cave-ericeira', slug: 'cave-ericeira', name: 'Cave (Ericeira)', nameEn: 'Cave (Ericeira)',
      region: 'Ericeira', regionEn: 'Ericeira', lat: 38.968, lon: -9.422,
      coastOrientation: 270,
      type: 'surf', difficulty: 'advanced', bestWind: 'E, SE', bestSwell: 'NW, W',
      description: 'Reef break pesado com ondas tubulares. Uma das ondas mais técnicas da Ericeira. Apenas para surfistas experientes.',
      descriptionEn: 'Heavy reef break with barreling waves. One of the most technical waves in Ericeira. For experienced surfers only.',
      facilities: ['Estacionamento limitado'],
      hazards: ['Rochas afiadas', 'Ondas pesadas', 'Correntes']
    },
  {
      id: 'pescadores-ericeira', slug: 'pescadores-ericeira', name: 'Pescadores (Ericeira)', nameEn: 'Pescadores (Ericeira)',
      region: 'Ericeira', regionEn: 'Ericeira', lat: 38.963, lon: -9.419,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'NW, W',
      description: 'Point break junto ao porto de pesca da Ericeira. Direita longa e consistente com fundo de rocha. Spot clássico da vila.',
      descriptionEn: 'Point break next to Ericeira\'s fishing port. Long and consistent right-hander with rock bottom. Classic village spot.',
      facilities: ['Estacionamento', 'Restaurantes', 'WC'],
      hazards: ['Rochas', 'Barcos de pesca', 'Locals']
    },
  {
      id: 'crazy-left', slug: 'crazy-left', name: 'Crazy Left (Ericeira)', nameEn: 'Crazy Left (Ericeira)',
      region: 'Ericeira', regionEn: 'Ericeira', lat: 38.958, lon: -9.418,
      coastOrientation: 270,
      type: 'surf', difficulty: 'advanced', bestWind: 'E, SE', bestSwell: 'NW, W',
      description: 'Esquerda tubular e rápida sobre reef. Uma das poucas esquerdas de qualidade da Ericeira. Técnica e perigosa. Experts apenas.',
      descriptionEn: 'Fast barreling left over reef. One of the few quality lefts in Ericeira. Technical and dangerous. Experts only.',
      facilities: [],
      hazards: ['Rochas', 'Ondas rápidas', 'Pouco profundo']
    },
  {
      id: 'meco', slug: 'meco', name: 'Praia do Meco', nameEn: 'Meco Beach',
      region: 'Sesimbra', regionEn: 'Sesimbra', lat: 38.473, lon: -9.188,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Praia selvagem ao sul da Lagoa de Albufeira. Beach break potente com ondas de qualidade. Ambiente naturista e natureza intocada.',
      descriptionEn: 'Wild beach south of Albufeira Lagoon. Powerful beach break with quality waves. Naturist atmosphere and untouched nature.',
      facilities: ['Estacionamento', 'Restaurante', 'WC'],
      hazards: ['Correntes fortes', 'Falésias', 'Sem vigilância']
    },
  {
      id: 'lagoa-santo-andre', slug: 'lagoa-santo-andre', name: 'Lagoa de Santo André', nameEn: 'Santo Andre Lagoon',
      region: 'Alentejo', regionEn: 'Alentejo', lat: 38.090, lon: -8.792,
      coastOrientation: 270,
      type: 'kitesurf', difficulty: 'beginner', bestWind: 'NW, N', bestSwell: 'Lagoa',
      description: 'Lagoa costeira enorme com água plana e vento térmico consistente. Perfeita para kitesurf e windsurf. Reserva natural com flamingos.',
      descriptionEn: 'Huge coastal lagoon with flat water and consistent thermal wind. Perfect for kitesurf and windsurf. Nature reserve with flamingos.',
      compatibleSports: ['kitesurf', 'windsurf', 'foil', 'sup'],
      facilities: ['Estacionamento', 'Escola kite', 'Restaurante', 'WC'],
      hazards: ['Maré baixa expõe bancos de areia']
    },
  {
      id: 'lagoa-sancha', slug: 'lagoa-sancha', name: 'Lagoa da Sancha', nameEn: 'Sancha Lagoon',
      region: 'Alentejo', regionEn: 'Alentejo', lat: 38.025, lon: -8.798,
      coastOrientation: 270,
      type: 'kitesurf', difficulty: 'beginner', bestWind: 'NW, N', bestSwell: 'Lagoa',
      description: 'Pequena lagoa natural entre Santo André e São Torpes. Água calma e vento térmico. Spot secreto de kitesurf do Alentejo.',
      descriptionEn: 'Small natural lagoon between Santo Andre and Sao Torpes. Calm water and thermal wind. Alentejo\'s secret kitesurf spot.',
      compatibleSports: ['kitesurf', 'foil', 'sup'],
      facilities: ['Estacionamento'],
      hazards: ['Acesso por estrada de terra', 'Maré baixa']
    },
  {
      id: 'pessegueiro', slug: 'pessegueiro', name: 'Ilha do Pessegueiro', nameEn: 'Pessegueiro Island',
      region: 'Alentejo', regionEn: 'Alentejo', lat: 37.831, lon: -8.796,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Praia com ilhota e forte histórico. Beach break consistente com ondas de qualidade. Um dos spots mais bonitos do Alentejo.',
      descriptionEn: 'Beach with islet and historic fort. Consistent beach break with quality waves. One of the most beautiful spots in Alentejo.',
      facilities: ['Estacionamento', 'Restaurante', 'WC'],
      hazards: ['Rochas junto ao forte', 'Correntes']
    },
  {
      id: 'garrão', slug: 'garrão', name: 'Praia do Garrão', nameEn: 'Garrao Beach',
      region: 'Faro', regionEn: 'Faro', lat: 36.970, lon: -7.960,
      coastOrientation: 180,
      type: 'surf', difficulty: 'beginner', bestWind: 'N, NW', bestSwell: 'S, SW',
      description: 'Praia extensa da Ria Formosa com ondas suaves. Ideal para iniciantes e longboard. Água quente e cristalina.',
      descriptionEn: 'Long Ria Formosa beach with gentle waves. Ideal for beginners and longboard. Warm crystal clear water.',
      compatibleSports: ['surf', 'sup', 'kitesurf'],
      facilities: ['Estacionamento', 'Restaurantes', 'WC'],
      hazards: ['Bancos de areia', 'Correntes na barra']
    },
  {
      id: 'falesia', slug: 'falesia', name: 'Praia da Falésia', nameEn: 'Falesia Beach',
      region: 'Albufeira', regionEn: 'Albufeira', lat: 37.075, lon: -8.153,
      coastOrientation: 180,
      type: 'surf', difficulty: 'beginner', bestWind: 'N, NW', bestSwell: 'S, SW',
      description: 'Praia icónica com falésias vermelhas de 40m. Beach break com múltiplos picos. Água quente e ondas suaves. Uma das praias mais fotografadas do Algarve.',
      descriptionEn: 'Iconic beach with 40m red cliffs. Beach break with multiple peaks. Warm water and gentle waves. One of the most photographed beaches in the Algarve.',
      compatibleSports: ['surf', 'bodyboard', 'sup'],
      blueFlag: true,
      facilities: ['Estacionamento', 'Hotéis', 'Restaurantes', 'WC'],
      hazards: ['Correntes', 'Quedas de falésia']
    },
  {
      id: 'tres-irmaos', slug: 'tres-irmaos', name: 'Praia dos Três Irmãos', nameEn: 'Tres Irmãos Beach',
      region: 'Alvor', regionEn: 'Alvor', lat: 37.122, lon: -8.601,
      coastOrientation: 180,
      type: 'surf', difficulty: 'beginner', bestWind: 'W, NW', bestSwell: 'S, SW',
      description: 'Praia de grutas e rochas com ondas suaves. Água quente e protegida. Ideal para famílias e iniciantes de surf.',
      descriptionEn: 'Beach with caves and rock formations with gentle waves. Warm protected water. Ideal for families and beginner surfers.',
      facilities: ['Estacionamento', 'Restaurantes', 'Hotel', 'WC'],
      hazards: ['Rochas submersas', 'Maré baixa']
    },
  {
      id: 'canavial', slug: 'canavial', name: 'Praia do Canavial', nameEn: 'Canavial Beach',
      region: 'Algarve', regionEn: 'Algarve', lat: 37.115, lon: -8.395,
      coastOrientation: 180,
      type: 'kitesurf', difficulty: 'beginner', bestWind: 'E, SE', bestSwell: 'Lagoa',
      description: 'Praia pouco conhecida entre a Ria Formosa e o mar. Água plana com vento térmico de leste. Kitesurf e foil sem multidão.',
      descriptionEn: 'Little-known beach between Ria Formosa and the sea. Flat water with east thermal wind. Kitesurf and foil with no crowd.',
      compatibleSports: ['kitesurf', 'foil'],
      facilities: ['Estacionamento'],
      hazards: ['Acesso por estrada de terra', 'Sem vigilância']
    },
  {
      id: 'mareta', slug: 'mareta', name: 'Praia da Mareta', nameEn: 'Mareta Beach',
      region: 'Sagres', regionEn: 'Sagres', lat: 37.006, lon: -8.940,
      coastOrientation: 180,
      type: 'surf', difficulty: 'beginner', bestWind: 'N, NW', bestSwell: 'S, SW',
      description: 'Praia virada a sul protegida do vento norte. Ondas suaves perfeitas para iniciantes. Água cristalina. Centro da vila de Sagres.',
      descriptionEn: 'South-facing beach sheltered from the north wind. Gentle waves perfect for beginners. Crystal clear water. Sagres town center.',
      facilities: ['Estacionamento', 'Restaurantes', 'Escola surf', 'WC'],
      hazards: ['Rochas nas pontas']
    },
  {
      id: 'machico', slug: 'machico', name: 'Machico', nameEn: 'Machico',
      region: 'Madeira', regionEn: 'Madeira', lat: 32.720, lon: -16.767,
      coastOrientation: 90,
      type: 'surf', difficulty: 'beginner', bestWind: 'N, NE', bestSwell: 'S, SE',
      description: 'A melhor praia de areia dourada da Madeira. Ondas suaves e consistentes. Água cristalina e falésias verdes. Ideal para iniciantes.',
      descriptionEn: 'The best golden sand beach in Madeira. Soft and consistent waves. Crystal clear water and green cliffs. Ideal for beginners.',
      facilities: ['Estacionamento', 'Escola surf', 'Restaurantes', 'WC'],
      hazards: ['Correntes', 'Multidão no verão']
    },
  {
      id: 'seixal-madeira', slug: 'seixal-madeira', name: 'Seixal', nameEn: 'Seixal',
      region: 'Madeira', regionEn: 'Madeira', lat: 32.813, lon: -17.107,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'S, SE', bestSwell: 'N, NW',
      description: 'Praia de calhau rolado entre montanhas verdes. Ondas consistentes na costa norte. Poços naturais de água cristalina. Cenário deslumbrante.',
      descriptionEn: 'Pebble beach between green mountains. Consistent waves on the north coast. Natural crystal clear water pools. Stunning scenery.',
      facilities: ['Estacionamento', 'Restaurante', 'WC'],
      hazards: ['Mar agitado', 'Calhau rolado']
    },
  {
      id: 'ponta-pargo', slug: 'ponta-pargo', name: 'Ponta do Pargo', nameEn: 'Ponta do Pargo',
      region: 'Madeira', regionEn: 'Madeira', lat: 32.817, lon: -17.267,
      coastOrientation: 270,
      type: 'big-wave', difficulty: 'expert', bestWind: 'N, NE', bestSwell: 'W, NW',
      description: 'O ponto mais ocidental da Madeira com ondas gigantes até 15m. Big wave spot para tow-in. Apenas profissionais. Farol icónico.',
      descriptionEn: 'Westernmost point of Madeira with giant waves up to 15m. Big wave tow-in spot. Professionals only. Iconic lighthouse.',
      facilities: ['Estacionamento limitado'],
      hazards: ['Ondas mortais', 'Rochas', 'Acesso difícil']
    },
  {
      id: 'madalena-mar', slug: 'madalena-mar', name: 'Madalena do Mar', nameEn: 'Madalena do Mar',
      region: 'Madeira', regionEn: 'Madeira', lat: 32.707, lon: -17.133,
      coastOrientation: 180,
      type: 'surf', difficulty: 'intermediate', bestWind: 'N, NE', bestSwell: 'S, SW',
      description: 'Reef break consistente na costa sul. Ondas de qualidade com crowd reduzido. Acesso fácil e cenário de bananeiras e montanhas.',
      descriptionEn: 'Consistent reef break on the south coast. Quality waves with reduced crowd. Easy access and scenery of banana trees and mountains.',
      facilities: ['Estacionamento', 'Restaurante', 'WC'],
      hazards: ['Rochas', 'Correntes']
    },
  {
      id: 'calhetas', slug: 'calhetas', name: 'Calhetas (São Miguel)', nameEn: 'Calhetas (Sao Miguel)',
      region: 'São Miguel', regionEn: 'Sao Miguel', lat: 37.821, lon: -25.599,
      coastOrientation: 270,
      type: 'surf', difficulty: 'advanced', bestWind: 'S, SE', bestSwell: 'N, NW',
      description: 'Point break esquerdo sobre lava vulcânica. Ondas longas e tubulares. Um dos spots mais famosos dos Açores. Apenas experts.',
      descriptionEn: 'Left-hand point break over volcanic lava. Long barreling waves. One of the most famous Azores spots. Experts only.',
      facilities: ['Estacionamento'],
      hazards: ['Rocha vulcânica afiada', 'Correntes', 'Acesso difícil']
    },
  {
      id: 'ribeira-quente', slug: 'ribeira-quente', name: 'Ribeira Quente (São Miguel)', nameEn: 'Ribeira Quente (Sao Miguel)',
      region: 'São Miguel', regionEn: 'Sao Miguel', lat: 37.728, lon: -25.308,
      coastOrientation: 180,
      type: 'surf', difficulty: 'intermediate', bestWind: 'N, NE', bestSwell: 'S, SW',
      description: 'Praia de areia negra com águas geotérmicas quentes. Ondas consistentes com fundo vulcânico. Restaurantes de peixe fresco junto à praia.',
      descriptionEn: 'Black sand beach with warm geothermal waters. Consistent waves over volcanic bottom. Fresh fish restaurants by the beach.',
      facilities: ['Estacionamento', 'Restaurantes', 'WC'],
      hazards: ['Rochas vulcânicas', 'Água quente junto à costa']
    },
  {
      id: 'formosa-santa-maria', slug: 'formosa-santa-maria', name: 'Formosa (Santa Maria)', nameEn: 'Formosa (Santa Maria)',
      region: 'Santa Maria', regionEn: 'Santa Maria', lat: 36.990, lon: -25.067,
      coastOrientation: 180,
      type: 'surf', difficulty: 'intermediate', bestWind: 'N, NE', bestSwell: 'S, SW',
      description: 'A melhor onda de Santa Maria. Direita longa sobre fundo de rocha. Água cristalina e cenário tropical. Praia de areia dourada.',
      descriptionEn: 'The best wave in Santa Maria. Long right-hander over rock bottom. Crystal clear water and tropical scenery. Golden sand beach.',
      facilities: ['Estacionamento', 'Restaurante', 'WC'],
      hazards: ['Rochas', 'Correntes']
    },
  {
      id: 'porto-martins', slug: 'porto-martins', name: 'Porto Martins (Terceira)', nameEn: 'Porto Martins (Terceira)',
      region: 'Terceira', regionEn: 'Terceira', lat: 38.676, lon: -27.058,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Point break consistente na costa este da Terceira. Ondas de qualidade com menos multidão que Santa Catarina. Fundo de lava.',
      descriptionEn: 'Consistent point break on Terceira\'s east coast. Quality waves with less crowd than Santa Catarina. Lava bottom.',
      facilities: ['Estacionamento'],
      hazards: ['Rochas', 'Correntes']
    },
  {
      id: 'cachorro-pico', slug: 'cachorro-pico', name: 'Cachorro (Pico)', nameEn: 'Cachorro (Pico)',
      region: 'Pico', regionEn: 'Pico', lat: 38.533, lon: -28.300,
      coastOrientation: 270,
      type: 'surf', difficulty: 'advanced', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Point break esquerdo na costa norte do Pico. Ondas tubulares sobre fundo vulcânico. Cenário dramático com a montanha do Pico ao fundo.',
      descriptionEn: 'Left-hand point break on Pico\'s north coast. Barreling waves over volcanic bottom. Dramatic scenery with Pico mountain in the background.',
      facilities: ['Estacionamento limitado'],
      hazards: ['Rochas', 'Acesso difícil', 'Ondas pesadas']
    },
  {
      id: 'faja-cubres', slug: 'faja-cubres', name: 'Fajã dos Cubres (São Jorge)', nameEn: 'Faja dos Cubres (Sao Jorge)',
      region: 'São Jorge', regionEn: 'Sao Jorge', lat: 38.633, lon: -27.967,
      coastOrientation: 270,
      type: 'surf', difficulty: 'intermediate', bestWind: 'E, SE', bestSwell: 'W, NW',
      description: 'Fajã (plataforma lávica) com point break esquerdo. Uma das ondas mais bonitas dos Açores. Lagoa interior de água salgada. Cenário único.',
      descriptionEn: 'Lava platform with left-hand point break. One of the most beautiful waves in the Azores. Interior saltwater lagoon. Unique scenery.',
      facilities: ['Estacionamento', 'Restaurante', 'WC'],
      hazards: ['Acesso por estrada íngreme', 'Rochas']
    },
    ];

export const getSpotBySlug = (slug: string): Spot | undefined =>
  spots.find(s => s.slug === slug);
