/**
 * Restore data files for local development
 * 
 * Run after git pull or fresh clone to restore data files:
 * 
 *   node scripts/restore-data.js
 * 
 * Data files are auto-generated by GitHub Actions (update-data.yml)
 * and stored in a separate backup location.
 */

const fs = require('fs');
const path = require('path');

const DATA_DIR = path.join(__dirname, '..', 'public', 'data');
const BACKUP_DIR = path.join(__dirname, '..', '.backup', 'data');

const DATA_FILES = [
  'conditions.json',
  'news.json',
  'dawn-patrol.json',
  'sitemap.json'
];

function restoreData() {
  console.log('🔄 Restaurando ficheiros de dados...\n');

  // Create data directory if it doesn't exist
  if (!fs.existsSync(DATA_DIR)) {
    fs.mkdirSync(DATA_DIR, { recursive: true });
    console.log('📁 Criado diretório: public/data/');
  }

  // Check for backup
  if (!fs.existsSync(BACKUP_DIR)) {
    console.log('⚠️  ATENÇÃO: Pasta de backup não encontrada.');
    console.log('   Execute os scripts de update para gerar dados locais:');
    console.log('   - npm run conditions:update');
    console.log('   - npm run news:generate');
    console.log('\n   Ou baixe os dados da última release do GitHub.');
    return;
  }

  let restored = 0;
  let missing = 0;

  for (const file of DATA_FILES) {
    const backupPath = path.join(BACKUP_DIR, file);
    const destPath = path.join(DATA_DIR, file);

    if (fs.existsSync(backupPath)) {
      fs.copyFileSync(backupPath, destPath);
      console.log(`✅ Restaurado: ${file}`);
      restored++;
    } else {
      console.log(`⚠️  Não encontrado no backup: ${file}`);
      missing++;
    }
  }

  console.log(`\n📊 Resumo: ${restored} restaurados, ${missing} em falta`);

  if (missing > 0) {
    console.log('\n💡 Para gerar dados em falta:');
    console.log('   npm run data:update');
  }
}

restoreData();