import type { NewsItem } from '@/types'
import { loadNews } from '@/lib/load-news'
import NewsArchiveClient from '@/components/news/NewsArchiveClient'
import type { Metadata } from 'next'

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params
  const isPt = locale === 'pt'

  return {
    title: isPt ? 'Notícias — VenTu' : 'News — VenTu',
    description: isPt
      ? 'Notícias automáticas sobre surf, kitesurf, windsurf e big wave em Portugal, geradas por IA.'
      : 'Automated news about surf, kitesurf, windsurf and big wave in Portugal, generated by AI.',
    alternates: {
      canonical: `/${locale}/news`,
      languages: {
        'pt': '/pt/news',
        'en': '/en/news',
      },
    },
  }
}

export default async function NewsPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params
  const news = await loadNews()

  if (news.length === 0) {
    const isPt = locale === 'pt'
    return (
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="text-center py-16 space-y-4">
          <p className="text-fg-subtle text-lg">
            {isPt
              ? 'Ainda não há notícias disponíveis. Volta mais tarde!'
              : 'No news available yet. Check back later!'}
          </p>
          <p className="text-fg-subtle/80 text-sm">
            {isPt
              ? 'As notícias são atualizadas automaticamente a cada 3 horas.'
              : 'News are automatically updated every 3 hours.'}
          </p>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen">
      <NewsArchiveClient news={news} locale={locale} />
    </div>
  )
}
