import { getTranslation } from '@/lib/i18n'
import { NewsItem } from '@/types'
import NewsCard from '@/components/news/NewsCard'
import { Newspaper } from 'lucide-react'

async function loadNews(): Promise<NewsItem[]> {
  try {
    // Read from the JSON file generated by update-news.js
    const fs = require('fs');
    const path = require('path');
    const filePath = path.join(process.cwd(), 'public/data/news.json');
    
    if (fs.existsSync(filePath)) {
      const data = fs.readFileSync(filePath, 'utf-8');
      const parsed = JSON.parse(data);
      
      if (Array.isArray(parsed) && parsed.length > 0) {
        // Check if data is not empty (has real titles)
        const validNews = parsed.filter((item: NewsItem) => 
          item.title && item.title.trim() !== ''
        );
        
        if (validNews.length > 0) {
          return validNews;
        }
      }
    }
  } catch (e) {
    console.warn('Failed to load news.json:', e);
  }
  
  // Fallback: return empty array (will show "no news" message)
  return [];
}

export default async function NewsPage({ params }: { params: { locale: string } }) {
  const { locale } = params
  const t = getTranslation(locale as any)
  const news = await loadNews()
  
  const isPt = locale === 'pt'

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-8">
      <div className="flex items-center gap-4">
        <Newspaper className="w-8 h-8 text-cyan-400" />
        <div>
          <h1 className="text-4xl font-bold text-white/90">{t.news.title}</h1>
          <p className="text-white/50 mt-1">
            {isPt ? 'Notícias automáticas sobre desportos náuticos' : 'Automated news about water sports'}
          </p>
        </div>
      </div>

      {news.length === 0 ? (
        <div className="text-center py-16 space-y-4">
          <Newspaper className="w-16 h-16 text-white/20 mx-auto" />
          <p className="text-white/40 text-lg">
            {isPt 
              ? 'Ainda não há notícias disponíveis. Volta mais tarde!' 
              : 'No news available yet. Check back later!'}
          </p>
          <p className="text-white/30 text-sm">
            {isPt 
              ? 'As notícias são atualizadas automaticamente a cada 3 horas.' 
              : 'News are automatically updated every 3 hours.'}
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {news.map((newsItem) => (
            <NewsCard key={newsItem.id} news={newsItem} locale={locale} />
          ))}
        </div>
      )}
    </div>
  )
}
